# Retrieval Evaluation

In [1]:
import os
from dotenv import load_dotenv
load_dotenv()
os.environ["HF_TOKEN"] = os.getenv("HF_TOKEN")

In [2]:
import pickle
cleaned_docs = []
with open("cleaned_docs.pkl", "rb") as f:
    cleaned_docs = pickle.load(f)

In [3]:
from langchain_huggingface import HuggingFaceEmbeddings

hf_embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-large-en-v1.5",
)

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

In [4]:
from langchain_chroma import Chroma

vectorstore = Chroma(
    persist_directory="./chroma_db",
    embedding_function=hf_embeddings, 
)

In [5]:
TEST_QUESTIONS = [
    {
        "id": "Q01", "level": 1, "source": "WHO",
        "question": "What are the three classes of pharmacological antihypertensive medications recommended by the WHO as an initial treatment?",
        "aspect_tested": "Direct list retrieval",
        "expected_answer": "Thiazide and thiazide-like agents, ACE inhibitors (ACEis)/angiotensin-receptor blockers (ARBs), and long-acting dihydropyridine calcium channel blockers (CCBs)."
    },
    {
        "id": "Q02", "level": 1, "source": "NICE",
        "question": 'According to the NICE guideline, what is the exact definition of "accelerated hypertension"?',
        "aspect_tested": "Glossary definition / exact terminology",
        "expected_answer": "A severe increase in blood pressure to 180/120 mmHg or higher with signs of retinal haemorrhage and/or papilloedema."
    },
    {
        "id": "Q03", "level": 1, "source": "NICE",
        "question": "What specific life-threatening symptoms require a same-day specialist referral under the NICE guidelines for a patient with a clinic blood pressure of 180/120 mmHg or higher?",
        "aspect_tested": "Specific criteria identification",
        "expected_answer": "New onset confusion, chest pain, signs of heart failure, or acute kidney injury."
    },
    {
        "id": "Q04", "level": 1, "source": "WHO",
        "question": "What four conditions must be met for nonphysician professionals to provide pharmacological treatment for hypertension according to the WHO?",
        "aspect_tested": "Strict preconditions within a specific section",
        "expected_answer": "Proper training, prescribing authority, specific management protocols, and physician oversight."
    },
    {
        "id": "Q05", "level": 1, "source": "NICE",
        "question": 'How does the NICE guideline define the "white-coat effect"?',
        "aspect_tested": "Concept definition",
        "expected_answer": "A discrepancy of more than 20/10 mmHg between clinic and average daytime ABPM or average HBPM blood pressure measurements at the time of diagnosis."
    },
    {
        "id": "Q06", "level": 2, "source": "NICE",
        "question": "If a patient's clinic blood pressure is 140/90 mmHg or higher, what are the exact sequential steps for taking further measurements during the consultation according to NICE?",
        "aspect_tested": "Procedural logic / sequential steps",
        "expected_answer": "Take a second measurement during the consultation. If the second measurement is substantially different from the first, take a third measurement. Record the lower of the last 2 measurements as the clinic blood pressure."
    },
    {
        "id": "Q07", "level": 2, "source": "WHO",
        "question": "Does the WHO recommend delaying the start of pharmacological treatment in order to perform a formal cardiovascular disease (CVD) risk assessment?",
        "aspect_tested": "Negative constraint / contextual caveats",
        "expected_answer": "No — CVD risk assessment is suggested only where feasible and should not delay treatment. If it may threaten timely initiation, it should be postponed and included in the follow-up strategy."
    },
    {
        "id": "Q08", "level": 2, "source": "NICE",
        "question": "What specific warnings does the NICE guideline provide regarding the use of salt substitutes containing potassium chloride?",
        "aspect_tested": "Exceptions and edge cases",
        "expected_answer": "Should not be used by older people, people with diabetes, pregnant women, people with kidney disease, and people taking some antihypertensive drugs such as ACE inhibitors and angiotensin II receptor blockers."
    },
    {
        "id": "Q09", "level": 2, "source": "WHO",
        "question": "What is the WHO's target systolic blood pressure treatment goal for high-risk patients (those with high CVD risk, diabetes mellitus, or chronic kidney disease)?",
        "aspect_tested": "Conditional numerical thresholds",
        "expected_answer": "The target systolic blood pressure goal is <130 mmHg."
    },
    {
        "id": "Q10", "level": 2, "source": "NICE",
        "question": "How does the NICE guideline differentiate the clinic blood pressure targets for adults aged under 80 compared to those aged 80 and over?",
        "aspect_tested": "Age-based threshold comparison",
        "expected_answer": "Under 80: target below 140/90 mmHg. 80 and over: target below 150/90 mmHg."
    },
    {
        "id": "Q11", "level": 3, "source": "NICE",
        "question": "Under the NICE Step 1 treatment recommendations, what is the correct initial medication for a 60-year-old patient of Black African family origin who does not have type 2 diabetes?",
        "aspect_tested": "Multi-variable conditional logic (age + ethnicity + comorbidity)",
        "expected_answer": "A calcium-channel blocker (CCB) should be offered."
    },
    {
        "id": "Q12", "level": 3, "source": "WHO",
        "question": 'According to the WHO\'s "Algorithm 2" (initiation of treatment not using a single-pill combination), what is the next step if a patient starting on a half-maximal dose of a CCB (like Amlodipine 5 mg) is not at their blood pressure goal after 4-6 weeks?',
        "aspect_tested": "Following algorithmic flowcharts / decision trees",
        "expected_answer": "Increase the CCB by doubling the dose (e.g., to Amlodipine 10 mg once a day)."
    },
    {
        "id": "Q13", "level": 3, "source": "NICE",
        "question": "In the NICE guideline's Step 4 treatment for resistant hypertension, how does the patient's blood potassium level dictate the choice of the fourth antihypertensive drug?",
        "aspect_tested": "Lab-value-dependent treatment branching",
        "expected_answer": "If potassium ≤4.5 mmol/l: consider further diuretic therapy with low-dose spironolactone. If potassium >4.5 mmol/l: consider an alpha-blocker or beta-blocker."
    },
    {
        "id": "Q14", "level": 3, "source": "WHO",
        "question": "What are the maternal and fetal risks of using renin-angiotensin-aldosterone system inhibitors (like ACEis or ARBs) during pregnancy according to the WHO, and how does this affect treatment algorithms?",
        "aspect_tested": "Synthesizing pathophysiology warnings with treatment contraindications",
        "expected_answer": "Associated with serious fetal toxicity, including renal and cardiac abnormalities and death. Strictly contraindicated in pregnancy — neither ACEi nor ARB should be given to pregnant women."
    },
    {
        "id": "Q15", "level": 3, "source": "NICE",
        "question": "How should a healthcare professional appropriately measure and manage blood pressure for a patient presenting with symptoms of postural hypotension, according to the NICE guideline?",
        "aspect_tested": "Multi-step clinical workflow and differential response logic",
        "expected_answer": "Measure lying/seated, then again after standing ≥1 minute. If systolic drops ≥20 mmHg or diastolic ≥10 mmHg: review medication, manage falls risk, measure subsequent readings standing, and consider specialist referral if symptoms persist."
    },
]

import pandas as pd
df_questions = pd.DataFrame(TEST_QUESTIONS)
df_questions.head()

,id,level,source,question,aspect_tested,expected_answer
0,Q01,1,WHO,What are the three classes of pharmacological ...,Direct list retrieval,"Thiazide and thiazide-like agents, ACE inhibit..."
1,Q02,1,NICE,"According to the NICE guideline, what is the e...",Glossary definition / exact terminology,A severe increase in blood pressure to 180/120...
2,Q03,1,NICE,What specific life-threatening symptoms requir...,Specific criteria identification,"New onset confusion, chest pain, signs of hear..."
3,Q04,1,WHO,What four conditions must be met for nonphysic...,Strict preconditions within a specific section,"Proper training, prescribing authority, specif..."
4,Q05,1,NICE,"How does the NICE guideline define the ""white-...",Concept definition,A discrepancy of more than 20/10 mmHg between ...

In [6]:
def retrieve_topk(query, k, vs=vectorstore):
    return vs.similarity_search_with_score(query, k=k)

In [7]:
def show_topk_comparison(question, ks=(3, 5, 10)):
    print(f"\n{'='*90}\nQUERY: {question}\n{'='*90}")
    for k in ks:
        results = retrieve_topk(question, k)
        print(f"\n--- Top-{k} ---")
        for rank, (doc, score) in enumerate(results, 1):
            meta = doc.metadata
            preview = doc.page_content[:400].replace("\n", " ")
            print(f"[{rank}] score={score:.4f} | "
                  f"{meta.get('document_name', '?')} "
                  f"page:{meta.get('page_number', '?')} "
                  f"(chunk_id={meta.get('chunk_id', '?')})")
            print(f"     {preview}...")

In [8]:
for qid in ["Q01", "Q06", "Q11"]:
    q = next(item["question"] for item in TEST_QUESTIONS if item["id"] == qid)
    show_topk_comparison(q, ks=(3, 5, 10))

==========================================================================================
QUERY: What are the three classes of pharmacological antihypertensive medications recommended by the WHO as an initial treatment?
==========================================================================================

--- Top-3 ---
[1] score=0.4778 | file1.pdf page:10 (chunk_id=file1.pdf_ch0003)
     WHO suggests pharmacological antihypertensive treatment of individuals without  cardiovascular disease but with high cardiovascular risk, diabetes mellitus, or chronic kidney  disease, and systolic blood pressure of 130–139 mmHg. Conditional recommendation, moderate- to high-certainty evidence  2. RECOMMENDATION ON LABORATORY TESTING When starting pharmacological therapy for hypertension, WHO sugg...
[2] score=0.4800 | file1.pdf page:9 (chunk_id=file1.pdf_ch0001)
     Executive summary More people die each year from cardiovascular diseases than from any other cause. Over three  quarters of heart disease and stroke-related deaths occur in low-income and middle-income countries.  Hypertension – or elevated blood pressure – is a serious medical condition that significantly increases the  risk of heart, brain, kidney and other diseases. Hypertension can be defined ...
[3] score=0.5121 | file1.pdf page:23 (chunk_id=file1.pdf_ch0024)
     or cerebrovascular disease. Hence, the absolute benefit of blood pressure lowering would be greatest in  those with the highest absolute risk of CVD (27).  3.4 Drug classes to be used as first-line agents To develop a recommendation that is practical and implementable by end-users, the evidence-to-decision  frameworks of PICO questions 4 and 5 (see Annex 4) were used to develop one recommendation....

--- Top-5 ---
[1] score=0.4778 | file1.pdf page:10 (chunk_id=file1.pdf_ch0003)
     WHO suggests pharmacological antihypertensive treatment of individuals without  cardiovascular disease but with high cardiovascular risk, diabetes mellitus, or chronic kidney  disease, and systolic blood pressure of 130–139 mmHg. Conditional recommendation, moderate- to high-certainty evidence  2. RECOMMENDATION ON LABORATORY TESTING When starting pharmacological therapy for hypertension, WHO sugg...
[2] score=0.4800 | file1.pdf page:9 (chunk_id=file1.pdf_ch0001)
     Executive summary More people die each year from cardiovascular diseases than from any other cause. Over three  quarters of heart disease and stroke-related deaths occur in low-income and middle-income countries.  Hypertension – or elevated blood pressure – is a serious medical condition that significantly increases the  risk of heart, brain, kidney and other diseases. Hypertension can be defined ...
[3] score=0.5121 | file1.pdf page:23 (chunk_id=file1.pdf_ch0024)
     or cerebrovascular disease. Hence, the absolute benefit of blood pressure lowering would be greatest in  those with the highest absolute risk of CVD (27).  3.4 Drug classes to be used as first-line agents To develop a recommendation that is practical and implementable by end-users, the evidence-to-decision  frameworks of PICO questions 4 and 5 (see Annex 4) were used to develop one recommendation....
[4] score=0.5220 | file1.pdf page:13 (chunk_id=file1.pdf_ch0006)
     drugs as well as single-pill combinations in this current guideline. Scope and objectives of the hypertension guideline The 2021 WHO hypertension guideline aims to provide the most current and relevant evidencebased global public health guidance on the initiation of treatment (with pharmacological agents) for  hypertension in adults. The recommendations target the general adult, non-pregnant, hype...
[5] score=0.5348 | file1.pdf page:9 (chunk_id=file1.pdf_ch0002)
     resource requirements and cost-effectiveness; health equity; acceptability, patient values and  preferences, and feasibility. Recommendations  1. RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF  PHARMACOLOGICAL TREATMENT WHO recommends initiation of pharmacological antihypertensive treatment of individuals  with a confirmed diagnosis of hypertension and systolic blood pressure of ≥140...

--- Top-10 ---
[1] score=0.4778 | file1.pdf page:10 (chunk_id=file1.pdf_ch0003)
     WHO suggests pharmacological antihypertensive treatment of individuals without  cardiovascular disease but with high cardiovascular risk, diabetes mellitus, or chronic kidney  disease, and systolic blood pressure of 130–139 mmHg. Conditional recommendation, moderate- to high-certainty evidence  2. RECOMMENDATION ON LABORATORY TESTING When starting pharmacological therapy for hypertension, WHO sugg...
[2] score=0.4800 | file1.pdf page:9 (chunk_id=file1.pdf_ch0001)
     Executive summary More people die each year from cardiovascular diseases than from any other cause. Over three  quarters of heart disease and stroke-related deaths occur in low-income and middle-income countries.  Hypertension – or elevated blood pressure – is a serious medical condition that significantly increases the  risk of heart, brain, kidney and other diseases. Hypertension can be defined ...
[3] score=0.5121 | file1.pdf page:23 (chunk_id=file1.pdf_ch0024)
     or cerebrovascular disease. Hence, the absolute benefit of blood pressure lowering would be greatest in  those with the highest absolute risk of CVD (27).  3.4 Drug classes to be used as first-line agents To develop a recommendation that is practical and implementable by end-users, the evidence-to-decision  frameworks of PICO questions 4 and 5 (see Annex 4) were used to develop one recommendation....
[4] score=0.5220 | file1.pdf page:13 (chunk_id=file1.pdf_ch0006)
     drugs as well as single-pill combinations in this current guideline. Scope and objectives of the hypertension guideline The 2021 WHO hypertension guideline aims to provide the most current and relevant evidencebased global public health guidance on the initiation of treatment (with pharmacological agents) for  hypertension in adults. The recommendations target the general adult, non-pregnant, hype...
[5] score=0.5348 | file1.pdf page:9 (chunk_id=file1.pdf_ch0002)
     resource requirements and cost-effectiveness; health equity; acceptability, patient values and  preferences, and feasibility. Recommendations  1. RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF  PHARMACOLOGICAL TREATMENT WHO recommends initiation of pharmacological antihypertensive treatment of individuals  with a confirmed diagnosis of hypertension and systolic blood pressure of ≥140...
[6] score=0.5629 | file1.pdf page:19 (chunk_id=file1.pdf_ch0015)
     3 Recommendations 3.1 Blood pressure threshold for initiation of pharmacological treatment 1. RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF  PHARMACOLOGICAL TREATMENT WHO recommends initiation of pharmacological antihypertensive treatment of individuals  with a confirmed diagnosis of hypertension and systolic blood pressure of ≥140 mmHg or  diastolic blood pressure of ≥90 mmHg. Stro...
[7] score=0.5760 | file1.pdf page:25 (chunk_id=file1.pdf_ch0028)
     laboratory testing, lost work time etc. are real but modest. Numerous modelling studies demonstrate  cost effectiveness of antihypertensive therapy, which is especially beneficial in LMICs where large  numbers of adults have untreated HTN, as long as medications are available at low cost. Models were  available from many countries, including Bangladesh, Ghana and Nigeria (37, 38, 39, 40).  3.5 Com...
[8] score=0.5800 | file1.pdf page:39 (chunk_id=file1.pdf_ch0052)
     Fig. 4 An approach for starting treatment not using a single-pill combination (i.e. with monotherapy or  free combination therapy) Pharmacological treatment to be initiated under the following circumstances: [ [ A diagnosis of HTN has already been made. [ [ Initiation of pharmacological HTN treatment should start no later than four weeks after diagnosis of HTN.  [ [ If BP level is high or there is...
[9] score=0.5863 | file1.pdf page:43 (chunk_id=file1.pdf_ch0062)
     (28)  Seeley A, Prynn J, Perera R, Street R, Davis D, Etyang AO. Pharmacotherapy for hypertension in  sub-Saharan Africa: a systematic review and network meta-analysis. BMC Med. 2020;18(1):75.  doi: 10.1186/s12916-020-01530-z.  (29)  Antihypertensive and Lipid-Lowering Treatment to Prevent Heart Attack Trial Collaborative  Research Group. Diuretic versus alpha-blocker as first-step antihypertensiv...
[10] score=0.5972 | file1.pdf page:13 (chunk_id=file1.pdf_ch0005)
     1 Introduction More people die each year from cardiovascular diseases than from any other cause. Over three quarters  of heart disease and stroke-related deaths occur in low-income and middle-income countries (1). Blood  pressure is the force exerted by circulating blood against the walls of the body’s arteries, the major blood  vessels in the body. Blood pressure is written as two numbers. The fi...

==========================================================================================
QUERY: If a patient's clinic blood pressure is 140/90 mmHg or higher, what are the exact sequential steps for taking further measurements during the consultation according to NICE?
==========================================================================================

--- Top-3 ---
[1] score=0.4234 | file2.pdf page:7 (chunk_id=file2.pdf_ch0095)
     taken from a seated position, repeat the measurements this time starting with the  person lying on their back. [2023]  1.1.8  Consider referring the person for further specialist assessment if blood pressure  measurements do not confirm postural hypotension despite suggestive  symptoms. [2023]  1.2 Diagnosing hypertension  1.2.1  When considering a diagnosis of hypertension, measure blood pressure...
[2] score=0.5110 | file2.pdf page:5 (chunk_id=file2.pdf_ch0093)
     Recommendations  People have the right to be involved in discussions and make informed decisions  about their care, as described in NICE's information on making decisions about your  care.  Making decisions using  strength (or certainty) of our recommendations, and has information about  prescribing medicines (including off-label use), professional guidelines, standards  and laws (including on con...
[3] score=0.5180 | file2.pdf page:8 (chunk_id=file2.pdf_ch0096)
     1.2.5  While waiting for confirmation of a diagnosis of hypertension, carry out:  • investigations for target organ damage (see recommendation 1.3.3), followed  by  • formal assessment of cardiovascular risk using a cardiovascular risk  assessment tool (see the section on full formal risk assessment in NICE's  guideline on cardiovascular disease). [2019]  1.2.6  When using ABPM to confirm a diagno...

--- Top-5 ---
[1] score=0.4234 | file2.pdf page:7 (chunk_id=file2.pdf_ch0095)
     taken from a seated position, repeat the measurements this time starting with the  person lying on their back. [2023]  1.1.8  Consider referring the person for further specialist assessment if blood pressure  measurements do not confirm postural hypotension despite suggestive  symptoms. [2023]  1.2 Diagnosing hypertension  1.2.1  When considering a diagnosis of hypertension, measure blood pressure...
[2] score=0.5110 | file2.pdf page:5 (chunk_id=file2.pdf_ch0093)
     Recommendations  People have the right to be involved in discussions and make informed decisions  about their care, as described in NICE's information on making decisions about your  care.  Making decisions using  strength (or certainty) of our recommendations, and has information about  prescribing medicines (including off-label use), professional guidelines, standards  and laws (including on con...
[3] score=0.5180 | file2.pdf page:8 (chunk_id=file2.pdf_ch0096)
     1.2.5  While waiting for confirmation of a diagnosis of hypertension, carry out:  • investigations for target organ damage (see recommendation 1.3.3), followed  by  • formal assessment of cardiovascular risk using a cardiovascular risk  assessment tool (see the section on full formal risk assessment in NICE's  guideline on cardiovascular disease). [2019]  1.2.6  When using ABPM to confirm a diagno...
[4] score=0.5232 | file2.pdf page:16 (chunk_id=file2.pdf_ch0104)
     hypertension (in which clinic and non-clinic blood pressure results are  conflicting). Be aware that the corresponding measurements for ABPM and HBPM  are 5 mmHg lower than for clinic measurements (see recommendation 1.2.8 for  diagnostic thresholds). [2019]  1.4.19  For people who choose to use HBPM, provide:  • training and advice on using home blood pressure monitors  • information about what t...
[5] score=0.5367 | file2.pdf page:6 (chunk_id=file2.pdf_ch0094)
     properly validated, maintained and regularly recalibrated according to  manufacturers' instructions. See the British and Irish Hypertension Society's  website for a list of validated blood pressure monitoring devices. [2004]  1.1.4  When measuring blood pressure in the clinic or in the home, standardise the  environment and provide a relaxed, temperate setting, with the person quiet and  seated, a...

--- Top-10 ---
[1] score=0.4234 | file2.pdf page:7 (chunk_id=file2.pdf_ch0095)
     taken from a seated position, repeat the measurements this time starting with the  person lying on their back. [2023]  1.1.8  Consider referring the person for further specialist assessment if blood pressure  measurements do not confirm postural hypotension despite suggestive  symptoms. [2023]  1.2 Diagnosing hypertension  1.2.1  When considering a diagnosis of hypertension, measure blood pressure...
[2] score=0.5110 | file2.pdf page:5 (chunk_id=file2.pdf_ch0093)
     Recommendations  People have the right to be involved in discussions and make informed decisions  about their care, as described in NICE's information on making decisions about your  care.  Making decisions using  strength (or certainty) of our recommendations, and has information about  prescribing medicines (including off-label use), professional guidelines, standards  and laws (including on con...
[3] score=0.5180 | file2.pdf page:8 (chunk_id=file2.pdf_ch0096)
     1.2.5  While waiting for confirmation of a diagnosis of hypertension, carry out:  • investigations for target organ damage (see recommendation 1.3.3), followed  by  • formal assessment of cardiovascular risk using a cardiovascular risk  assessment tool (see the section on full formal risk assessment in NICE's  guideline on cardiovascular disease). [2019]  1.2.6  When using ABPM to confirm a diagno...
[4] score=0.5232 | file2.pdf page:16 (chunk_id=file2.pdf_ch0104)
     hypertension (in which clinic and non-clinic blood pressure results are  conflicting). Be aware that the corresponding measurements for ABPM and HBPM  are 5 mmHg lower than for clinic measurements (see recommendation 1.2.8 for  diagnostic thresholds). [2019]  1.4.19  For people who choose to use HBPM, provide:  • training and advice on using home blood pressure monitors  • information about what t...
[5] score=0.5367 | file2.pdf page:6 (chunk_id=file2.pdf_ch0094)
     properly validated, maintained and regularly recalibrated according to  manufacturers' instructions. See the British and Irish Hypertension Society's  website for a list of validated blood pressure monitoring devices. [2004]  1.1.4  When measuring blood pressure in the clinic or in the home, standardise the  environment and provide a relaxed, temperate setting, with the person quiet and  seated, a...
[6] score=0.5439 | file2.pdf page:24 (chunk_id=file2.pdf_ch0112)
     1.5 Identifying who to refer for same-day specialist  review  1.5.1  If a person has severe hypertension (clinic blood pressure of 180/120 mmHg or  higher), but no symptoms or signs indicating same-day referral (see  recommendation 1.5.2), carry out investigations for target organ damage (see  recommendation 1.3.3) as soon as possible:  • If target organ damage is identified, consider starting ant...
[7] score=0.5482 | file2.pdf page:51 (chunk_id=file2.pdf_ch0139)
     Update information  February 2026: We added recommendation 1.2.11 to offer advice on healthy living to  people who have raised blood pressure but have not been diagnosed with hypertension.  November 2023: We updated recommendations 1.1.5, 1.1.6 and 1.4.16 and made 2 new  recommendations (1.1.7 and 1.1.8) on how to measure and manage postural hypotension  (see the February 2023 surveillance report)...
[8] score=0.5858 | file2.pdf page:10 (chunk_id=file2.pdf_ch0098)
     1.3 Assessing cardiovascular risk and target organ  damage  For guidance on the early identification and management of chronic kidney disease, see  NICE's guideline on chronic kidney disease.  1.3.1  Use a formal estimation of cardiovascular risk to discuss prognosis and  healthcare options with people with hypertension, both for raised blood pressure  and other modifiable risk factors. [2004]  1....
[9] score=0.5885 | file2.pdf page:9 (chunk_id=file2.pdf_ch0097)
     1.2.10  If hypertension is not diagnosed, measure the person's clinic blood pressure at  least every 5 years subsequently, and consider measuring it more frequently if  the person's clinic blood pressure is less than 140/90 mmHg but still raised.  [2011]  1.2.11  Offer advice on healthy living in line with the NHS information on healthy living to  people who have raised blood pressure but have not...
[10] score=0.6006 | file2.pdf page:15 (chunk_id=file2.pdf_ch0103)
     • hypertension (with or without type 2  diabetes) or  • type 1 diabetes (regardless of  albumin to creatinine ratio)  Below  150/90  Recommendation 1.4.21  NICE's guideline on type 1  diabetes in adults  (recommendation 1.13.8)  • chronic kidney disease plus albumin  to creatinine ratio less than 70 mg/ mmol  Below  140/90  NICE's guideline on chronic kidney  disease (recommendation 1.6.1)  • chro...

==========================================================================================
QUERY: Under the NICE Step 1 treatment recommendations, what is the correct initial medication for a 60-year-old patient of Black African family origin who does not have type 2 diabetes?
==========================================================================================

--- Top-3 ---
[1] score=0.4649 | file2.pdf page:43 (chunk_id=file2.pdf_ch0131)
     people of Black African or African–Caribbean family origin). The committee discussed the  evidence for this and agreed that it was sufficient to support and retain this  recommendation. The committee agreed it should be broadened to include the choice of  an ACE inhibitor or an angiotensin II receptor blocker (ARB; also referred to as A-type  drugs), because they are now cost equivalent, and the c...
[2] score=0.5330 | file2.pdf page:42 (chunk_id=file2.pdf_ch0130)
     Step 1 treatment  Recommendations 1.4.32 to 1.4.39  Why the committee made the recommendations  The committee reviewed the evidence for starting treatment for primary hypertension with  a single antihypertensive medicine compared with starting with 2 antihypertensive  medicines at once (dual therapy). Additionally, the committee reviewed the evidence on  whether specific subgroups of people with h...
[3] score=0.5899 | file2.pdf page:12 (chunk_id=file2.pdf_ch0100)
     For a short explanation of why the committee deleted the recommendation on  relaxation therapies and how this might affect practice, see the rationale and impact  section on relaxation therapies.  Full details of the evidence and the committee's discussion are in evidence review H:  relaxation therapies.  Starting antihypertensive drug treatment  NICE has produced a patient decision aid on treatme...

--- Top-5 ---
[1] score=0.4649 | file2.pdf page:43 (chunk_id=file2.pdf_ch0131)

In [31]:

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from utils import prepare_metadata

CONFIG_A = {"chunk_size": 600, "chunk_overlap": 100, "name": "A_600_100"}
CONFIG_B = {"chunk_size": 800, "chunk_overlap": 200, "name": "B_800_200"}
CONFIG_C = {"chunk_size": 900, "chunk_overlap": 150, "name": "C_900_150"}
CONFIG_D = {"chunk_size": 400, "chunk_overlap": 50, "name": "D_400_50"}

splitter_a = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=CONFIG_A["chunk_size"],
    chunk_overlap=CONFIG_A["chunk_overlap"],
)

splitter_b = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=CONFIG_B["chunk_size"],
    chunk_overlap=CONFIG_B["chunk_overlap"],
)

splitter_c = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=CONFIG_C["chunk_size"],
    chunk_overlap=CONFIG_C["chunk_overlap"],
)

splitter_d = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=CONFIG_D["chunk_size"],
    chunk_overlap=CONFIG_D["chunk_overlap"],
)

chunks_a = splitter_a.split_documents(cleaned_docs)
chunks_b = splitter_b.split_documents(cleaned_docs)
chunks_c = splitter_c.split_documents(cleaned_docs)
chunks_d = splitter_d.split_documents(cleaned_docs)

chunks_a = prepare_metadata(chunks_a)
chunks_b = prepare_metadata(chunks_b)
chunks_c = prepare_metadata(chunks_c)
chunks_d = prepare_metadata(chunks_d)

print(f"Config A chunk count: {len(chunks_a)}")
print(f"Config B chunk count: {len(chunks_b)}")
print(f"Config C chunk count: {len(chunks_c)}")
print(f"Config D chunk count: {len(chunks_d)}")

Config A chunk count: 140
Config B chunk count: 121
Config C chunk count: 112
Config D chunk count: 232

In [10]:
vectorstore_a = Chroma.from_documents(
    chunks_a,
    hf_embeddings,
    persist_directory="chroma_db_configA",
    collection_name="config_a",
    collection_metadata={"hnsw:space": "cosine"},
)

# vectorstore_a = Chroma(
#     persist_directory="./chroma_db_configA",
#     embedding_function=hf_embeddings,
#     collection_name="config_a",
#      collection_metadata={"hnsw:space": "cosine"}, 
# )

In [11]:
vectorstore_b = Chroma.from_documents(
    chunks_b,
    hf_embeddings,
    persist_directory="chroma_db_configB",
    collection_name="config_b",
    collection_metadata={"hnsw:space": "cosine"}
)
# vectorstore_b = Chroma(
#     persist_directory="./chroma_db_configB",
#     embedding_function=hf_embeddings,
#     collection_name="config_b" 
# )

In [12]:
vectorstore_c = Chroma.from_documents(
    chunks_c,
    hf_embeddings,
    persist_directory="chroma_db_configC",
    collection_name="config_c",
    collection_metadata={"hnsw:space": "cosine"}
)

# vectorstore_c = Chroma(
#     persist_directory="./chroma_db_configC",
#     embedding_function=hf_embeddings,
#     collection_name="config_c" 
# )

In [32]:
vectorstore_d = Chroma.from_documents(
    chunks_d,
    hf_embeddings,
    persist_directory="chroma_db_configD",
    collection_name="config_d",
    collection_metadata={"hnsw:space": "cosine"}
)

In [33]:
vectorstore_d.similarity_search("what's hypertension?")

[Document(id='dc0d72c3-b3ea-4bf2-9feb-14d19bd3368f', metadata={'page_number': 13, 'document_name': 'file1.pdf', 'chunk_id': 'file1.pdf_ch0006', 'source_url': './files\\file1.pdf'}, page_content='1 Introduction\nMore people die each year from cardiovascular diseases than from any other cause. Over three quarters \nof heart disease and stroke-related deaths occur in low-income and middle-income countries (1). Blood \npressure is the force exerted by circulating blood against the walls of the body’s arteries, the major blood \nvessels in the body. Blood pressure is written as two numbers. The first number (systolic) represents the \npressure in blood vessels when the heart contracts or beats. The second number (diastolic) represents \nthe pressure in the vessels when the heart rests between beats. Hypertension – or elevated blood \npressure – is a serious medical condition that significantly increases the risk of diseases of the heart, \nbrain, kidneys and other organs (2). Hypertension can be defined using specific systolic and diastolic \nblood pressure levels or reported use of antihypertensive medications. An estimated 1.4 billion people \nworldwide have high blood pressure, but just 14% have it under control (2). However, cost-effective \ntreatment options do exist.\nA World Health Organization (WHO) guideline dealing specifically with raised blood pressure was last \npublished more than 20 years ago – in 1999 – and is now outdated. In 2007, a comprehensive guideline \non cardiovascular risk included some recommendations on hypertension but this also needs revision \nand updating in the light of new evidence and practice (3). Guidance is particularly needed on some \ncontroversial issues, such as when to start treatment and whether laboratory testing and cardiovascular \nrisk assessment are needed prior to starting treatment. In the past decade, WHO has included diagnosis \nand management of hypertension in a total cardiovascular risk approach as part of the WHO package \nof essential noncommunicable disease (NCD) Interventions (WHO PEN) 2007, 2010 and 2013. However,'),
 Document(id='b36ea8a8-e948-4d76-b261-f62a6df20b29', metadata={'page_number': 48, 'document_name': 'file2.pdf', 'source_url': './files\\file2.pdf', 'chunk_id': 'file2.pdf_ch0224'}, page_content="Context \nHigh blood pressure (hypertension) is one of the most important, treatable causes of \npremature morbidity and mortality in the world. It is a major risk factor for stroke, \nmyocardial infarction, heart failure, chronic kidney disease, cognitive decline and \npremature death. In 2015, it was reported that high blood pressure affected more than 1\xa0in \n4\xa0adults in England (31% of men; 26% of women) – around 13.5\xa0million people – and \ncontributed to 75,000\xa0deaths. The clinical management of hypertension accounts for 12% \nof visits to primary care and up to £2.1\xa0billion of healthcare expenditure. Managing the \ncardiovascular events caused by hypertension also consumes considerable resources. \nThe guideline covers adults (over 18\xa0years) with suspected or diagnosed hypertension, \nincluding those with type\xa02 diabetes. \n2019 update \nBetween 2010 and 2020, progress has been made to improve the diagnosis and \nmanagement of hypertension: the population average blood pressure in England has fallen \nby about 3\xa0mmHg systolic and the proportion of adults with untreated high blood pressure \nhas decreased. However, the Public Health England Blood Pressure Action Plan called for \nfurther action to reduce the population average blood pressure by 5\xa0mmHg through \nimproved prevention, detection and management (Public Health England's Tackling high \nblood pressure: from evidence into action, 2015 and Tackling high blood pressure: an \nupdate, 2018). \nSince the publication of the 2011 \npublished in key areas of management; in particular, the optimal method and threshold for \ndiagnosis of hypertension, managing blood pressure in lower risk populations and reducing \nblood pressure to lower targets in people with hypertension (including those with type\xa02"),
 Document(id='cff9c2ec-8bbb-409c-bb10-5ece458cd003', metadata={'source_url': './files\\file1.pdf', 'page_number': 9, 'chunk_id': 'file1.pdf_ch0001', 'document_name': 'file1.pdf'}, page_content='Executive summary\nMore people die each year from cardiovascular diseases than from any other cause. Over three \nquarters of heart disease and stroke-related deaths occur in low-income and middle-income countries. \nHypertension – or elevated blood pressure – is a serious medical condition that significantly increases the \nrisk of heart, brain, kidney and other diseases. Hypertension can be defined using specific systolic and \ndiastolic blood pressure levels or reported use of antihypertensive medications. An estimated 1.4 billion \npeople worldwide have high blood pressure, but just 14% have it under control. However, cost-effective \ntreatment options do exist.\nIn this guideline, the World Health Organization (WHO) provides the most current and relevant \nevidence-based global public health guidance on the initiation of treatment with pharmacological \nagents for hypertension in adults. The recommendations target adult, non-pregnant patients who were \nappropriately diagnosed with hypertension and counselled about life-style modifications. \nThe guideline provides new recommendations on the threshold for the initiation of pharmacological \ntreatment for hypertension, as well as recommendations on intervals for follow up, target blood \npressure to be achieved for control, and the cadre of health care workers who may initiate treatment. \nThe guideline provides the basis for deciding whether to initiate treatment with monotherapy, dual \ntherapy or single-pill combinations, as well as guidance for countries selecting medicines and algorithms \nfor hypertension control for their national guidelines for hypertension management.\nThe guideline was developed in accordance with the WHO Handbook for Guideline Development. In \nbrief, the WHO Steering Group, in collaboration with the Guideline Development Group, developed \nkey questions and rated outcomes to identify those critical for the development of the guideline. \nConflicts of interest were handled in line with the current Compliance, Risk Management and Ethics'),
 Document(id='e4a170dd-7bd8-4120-bdca-f3439c5ac20f', metadata={'document_name': 'file2.pdf', 'source_url': './files\\file2.pdf', 'chunk_id': 'file2.pdf_ch0169', 'page_number': 25}, page_content='Terms used in this guideline \nThis section defines terms that have been used in a particular way for this guideline. For \nother definitions see the NICE glossary. \nAccelerated hypertension \nA severe increase in blood pressure to 180/120\xa0mmHg or higher (and often over 220/\n120\xa0mmHg) with signs of retinal haemorrhage and/or papilloedema (swelling of the optic \nnerve). It is usually associated with new or progressive target organ damage and is also \nknown as malignant hypertension. \nEstablished cardiovascular disease \nMedical history of ischaemic heart disease, cerebrovascular disease, peripheral vascular \ndisease, aortic aneurysm or heart failure. Cardiovascular disease is a general term for \nconditions affecting the heart or blood vessels. It is usually associated with a build-up of \nfatty deposits inside the arteries (atherosclerosis) and an increased risk of blood clots. It \ncan also be associated with damage to arteries in organs such as the brain, heart, kidneys \nand eyes through deposition of glassy material within the artery walls (arteriosclerosis). \nCardiovascular disease is 1 of the main causes of death and disability in the UK, but it can \noften largely be prevented by leading a healthy lifestyle. \nMasked hypertension \nClinic blood pressure measurements are normal (less than 140/90\xa0mmHg), but blood \npressure measurements are higher when taken outside the clinic using average daytime \nambulatory blood pressure monitoring (ABPM) or average home blood pressure monitoring \n(HBPM) blood pressure measurements. \nPersistent hypertension \nHigh blood pressure at repeated clinical encounters. \nStage\xa01 hypertension')]

In [14]:
def compare_configs(question, k=5):
    print(f"\n{'='*90}\nQUERY: {question}\n{'='*90}")
    for name, vs in [(CONFIG_A["name"], vectorstore_a), (CONFIG_B["name"], vectorstore_b)]:
        print(f"\n--- Config {name} (Top-{k}) ---")
        for rank, (doc, score) in enumerate(retrieve_topk(question, k, vs), 1):
            m = doc.metadata
            print(f"[{rank}] score={score:.4f} | file: {m.get('document_name')} | page: {m.get('page_number')} | " 
                  f"chunk_id={m.get('chunk_id')}")
            print(f"     {doc.page_content.replace(chr(10), ' ')}...")

for qid in ["Q01", "Q06", "Q11"]:
    q = next(x["question"] for x in TEST_QUESTIONS if x["id"] == qid)
    compare_configs(q, k=5)

==========================================================================================
QUERY: What are the three classes of pharmacological antihypertensive medications recommended by the WHO as an initial treatment?
==========================================================================================

--- Config A_600_100 (Top-5) ---
[1] score=0.2389 | file: file1.pdf | page: 10 | chunk_id=file1.pdf_ch0003
     WHO suggests pharmacological antihypertensive treatment of individuals without  cardiovascular disease but with high cardiovascular risk, diabetes mellitus, or chronic kidney  disease, and systolic blood pressure of 130–139 mmHg. Conditional recommendation, moderate- to high-certainty evidence  2. RECOMMENDATION ON LABORATORY TESTING When starting pharmacological therapy for hypertension, WHO suggests obtaining tests to  screen for comorbidities and secondary hypertension, but only when testing does not delay  or impede starting treatment. Conditional recommendation, low-certainty evidence 3. RECOMMENDATION ON CARDIOVASCULAR DISEASE RISK ASSESSMENT  WHO suggests cardiovascular disease risk assessment at or after the initiation of  pharmacological treatment for hypertension, but only where this is feasible and does not  delay treatment. Conditional recommendation, low-certainty evidence 4. RECOMMENDATION ON DRUG CLASSES TO BE USED AS FIRST-LINE AGENTS For adults with hypertension requiring pharmacological treatment, WHO recommends the  use of drugs from any of the following three classes of pharmacological antihypertensive  medications as an initial treatment:  1. thiazide and thiazide-like agents 2. angiotensin-converting enzyme inhibitors (ACEis)/angiotensin-receptor blockers (ARBs) 3. long-acting dihydropyridine calcium channel blockers (CCBs). Strong recommendation, high-certainty evidence 5. RECOMMENDATION ON COMBINATION THERAPY For adults with hypertension requiring pharmacological treatment, WHO suggests  combination therapy, preferably with a single-pill combination (to improve adherence and  persistence), as an initial treatment. Antihypertensive medications used in combination  therapy should be chosen from the following three drug classes: diuretics (thiazide or  thiazide-like), angiotensin-converting enzyme inhibitors (ACEis)/angiotensin-receptor  blockers (ARBs), and long-acting dihydropyridine calcium channel blockers (CCBs). Conditional recommendation, moderate-certainty evidence 6. RECOMMENDATIONS ON TARGET BLOOD PRESSURE WHO recommends a target blood pressure treatment goal of <140/90 mmHg in all patients  with hypertension without comorbidities. Strong recommendation, moderate-certainty evidence...
[2] score=0.2400 | file: file1.pdf | page: 9 | chunk_id=file1.pdf_ch0001
     Executive summary More people die each year from cardiovascular diseases than from any other cause. Over three  quarters of heart disease and stroke-related deaths occur in low-income and middle-income countries.  Hypertension – or elevated blood pressure – is a serious medical condition that significantly increases the  risk of heart, brain, kidney and other diseases. Hypertension can be defined using specific systolic and  diastolic blood pressure levels or reported use of antihypertensive medications. An estimated 1.4 billion  people worldwide have high blood pressure, but just 14% have it under control. However, cost-effective  treatment options do exist. In this guideline, the World Health Organization (WHO) provides the most current and relevant  evidence-based global public health guidance on the initiation of treatment with pharmacological  agents for hypertension in adults. The recommendations target adult, non-pregnant patients who were  appropriately diagnosed with hypertension and counselled about life-style modifications.  The guideline provides new recommendations on the threshold for the initiation of pharmacological  treatment for hypertension, as well as recommendations on intervals for follow up, target blood  pressure to be achieved for control, and the cadre of health care workers who may initiate treatment.  The guideline provides the basis for deciding whether to initiate treatment with monotherapy, dual  therapy or single-pill combinations, as well as guidance for countries selecting medicines and algorithms  for hypertension control for their national guidelines for hypertension management. The guideline was developed in accordance with the WHO Handbook for Guideline Development. In  brief, the WHO Steering Group, in collaboration with the Guideline Development Group, developed  key questions and rated outcomes to identify those critical for the development of the guideline.  Conflicts of interest were handled in line with the current Compliance, Risk Management and Ethics  (CRE) policy and all members of the GDG were asked to fill in the standard WHO Declaration of Interest  (DOI) forms, which were reviewed. An overview of systematic reviews of the evidence was used to build  summary of findings tables according to the Grading of Recommendations, Assessment, Development  and Evaluations (GRADE) approach. The Guideline Development Group developed recommendations,  considering the certainty of the evidence; the balance between desirable and undesirable effects;  resource requirements and cost-effectiveness; health equity; acceptability, patient values and  preferences, and feasibility. Recommendations  1. RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF  PHARMACOLOGICAL TREATMENT WHO recommends initiation of pharmacological antihypertensive treatment of individuals  with a confirmed diagnosis of hypertension and systolic blood pressure of ≥140 mmHg or...
[3] score=0.2560 | file: file1.pdf | page: 23 | chunk_id=file1.pdf_ch0024
     or cerebrovascular disease. Hence, the absolute benefit of blood pressure lowering would be greatest in  those with the highest absolute risk of CVD (27).  3.4 Drug classes to be used as first-line agents To develop a recommendation that is practical and implementable by end-users, the evidence-to-decision  frameworks of PICO questions 4 and 5 (see Annex 4) were used to develop one recommendation.  4. RECOMMENDATION ON DRUG CLASSES TO BE USED AS FIRST-LINE AGENTS For adults with hypertension requiring pharmacological treatment, WHO recommends the  use of drugs from any of the following three classes of pharmacological antihypertensive  medications as an initial treatment:  1. thiazide and thiazide-like agents 2. angiotensin-converting enzyme inhibitors (ACEis)/angiotensin-receptor blockers (ARBs) 3. long-acting dihydropyridine calcium channel blockers (CCBs). Strong recommendation, high-certainty evidence Implementation remarks: [ [ Long-acting antihypertensives are preferred. [ [ Examples of indications to consider specific agents include diuretics or CCBs in patients over  65 years or those of African descent, beta-blockers in ischaemic heart disease, ACEis/ARBs in  patients with severe proteinuria, diabetes mellitus, heart failure or kidney disease. RECOMMENDATIONS 11...
[4] score=0.2610 | file: file1.pdf | page: 13 | chunk_id=file1.pdf_ch0006
     drugs as well as single-pill combinations in this current guideline. Scope and objectives of the hypertension guideline The 2021 WHO hypertension guideline aims to provide the most current and relevant evidencebased global public health guidance on the initiation of treatment (with pharmacological agents) for  hypertension in adults. The recommendations target the general adult, non-pregnant, hypertensive  population.  Although several countries and professional societies have guidelines on the topic of hypertension,  these are specific to the population of that particular country or the specific setting or constituency of  the professional society. Recent shifts in hypertension management, such as moving away from using  beta-blockers as a first-line agent or the increased research and adoption of combination therapies  and single-pill combinations, are all additional reasons for new guidance. The Guideline for the  pharmacological treatment of hypertension in adults will be the first global guideline in the past two  decades on the topic and will have specific relevance to low- and middle-income countries (LMICs).  The guideline provides new recommendations on the threshold for the initiation of pharmacological  treatment for hypertension, recommendations on intervals for follow up, target blood pressure to be  achieved for control, and the cadre of health care workers who may initiate treatment. It provides  the basis for deciding whether to initiate treatment with monotherapy, dual therapy, or single-pill  combination, as well as guidance for countries on selecting medicines for hypertension control in their  national guidelines for hypertension management. INTRODUCTION 1...
[5] score=0.2674 | file: file1.pdf | page: 9 | chunk_id=file1.pdf_ch0002
     resource requirements and cost-effectiveness; health equity; acceptability, patient values and  preferences, and feasibility. Recommendations  1. RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF  PHARMACOLOGICAL TREATMENT WHO recommends initiation of pharmacological antihypertensive treatment of individuals  with a confirmed diagnosis of hypertension and systolic blood pressure of ≥140 mmHg or  diastolic blood pressure of ≥90 mmHg. Strong recommendation, moderate- to high-certainty evidence WHO recommends pharmacological antihypertensive treatment of individuals with existing  cardiovascular disease and systolic blood pressure of 130–139 mmHg. Strong recommendation, moderate- to high-certainty evidence EXECUTIVE SUMMARY...

--- Config B_800_200 (Top-5) ---
[1] score=0.2186 | file: file1.pdf | page: 23 | chunk_id=file1.pdf_ch0018
     For adults with hypertension requiring pharmacological treatment, WHO recommends the  use of drugs from any of the following three classes of pharmacological antihypertensive  medications as an initial treatment:  1. thiazide and thiazide-like agents 2. angiotensin-converting enzyme inhibitors (ACEis)/angiotensin-receptor blockers (ARBs) 3. long-acting dihydropyridine calcium channel blockers (CCBs). Strong recommendation, high-certainty evidence Implementation remarks: [ [ Long-acting antihypertensives are preferred. [ [ Examples of indications to consider specific agents include diuretics or CCBs in patients over  65 years or those of African descent, beta-blockers in ischaemic heart disease, ACEis/ARBs in  patients with severe proteinuria, diabetes mellitus, heart failure or kidney disease. RECOMMENDATIONS 11...
[2] score=0.2389 | file: file1.pdf | page: 10 | chunk_id=file1.pdf_ch0002
     WHO suggests pharmacological antihypertensive treatment of individuals without  cardiovascular disease but with high cardiovascular risk, diabetes mellitus, or chronic kidney  disease, and systolic blood pressure of 130–139 mmHg. Conditional recommendation, moderate- to high-certainty evidence  2. RECOMMENDATION ON LABORATORY TESTING When starting pharmacological therapy for hypertension, WHO suggests obtaining tests to  screen for comorbidities and secondary hypertension, but only when testing does not delay  or impede starting treatment. Conditional recommendation, low-certainty evidence 3. RECOMMENDATION ON CARDIOVASCULAR DISEASE RISK ASSESSMENT  WHO suggests cardiovascular disease risk assessment at or after the initiation of  pharmacological treatment for hypertension, but only where this is feasible and does not  delay treatment. Conditional recommendation, low-certainty evidence 4. RECOMMENDATION ON DRUG CLASSES TO BE USED AS FIRST-LINE AGENTS For adults with hypertension requiring pharmacological treatment, WHO recommends the  use of drugs from any of the following three classes of pharmacological antihypertensive  medications as an initial treatment:  1. thiazide and thiazide-like agents 2. angiotensin-converting enzyme inhibitors (ACEis)/angiotensin-receptor blockers (ARBs) 3. long-acting dihydropyridine calcium channel blockers (CCBs). Strong recommendation, high-certainty evidence 5. RECOMMENDATION ON COMBINATION THERAPY For adults with hypertension requiring pharmacological treatment, WHO suggests  combination therapy, preferably with a single-pill combination (to improve adherence and  persistence), as an initial treatment. Antihypertensive medications used in combination  therapy should be chosen from the following three drug classes: diuretics (thiazide or  thiazide-like), angiotensin-converting enzyme inhibitors (ACEis)/angiotensin-receptor  blockers (ARBs), and long-acting dihydropyridine calcium channel blockers (CCBs). Conditional recommendation, moderate-certainty evidence 6. RECOMMENDATIONS ON TARGET BLOOD PRESSURE WHO recommends a target blood pressure treatment goal of <140/90 mmHg in all patients  with hypertension without comorbidities. Strong recommendation, moderate-certainty evidence...
[3] score=0.2400 | file: file1.pdf | page: 9 | chunk_id=file1.pdf_ch0001
     Executive summary More people die each year from cardiovascular diseases than from any other cause. Over three  quarters of heart disease and stroke-related deaths occur in low-income and middle-income countries.  Hypertension – or elevated blood pressure – is a serious medical condition that significantly increases the  risk of heart, brain, kidney and other diseases. Hypertension can be defined using specific systolic and  diastolic blood pressure levels or reported use of antihypertensive medications. An estimated 1.4 billion  people worldwide have high blood pressure, but just 14% have it under control. However, cost-effective  treatment options do exist. In this guideline, the World Health Organization (WHO) provides the most current and relevant  evidence-based global public health guidance on the initiation of treatment with pharmacological  agents for hypertension in adults. The recommendations target adult, non-pregnant patients who were  appropriately diagnosed with hypertension and counselled about life-style modifications.  The guideline provides new recommendations on the threshold for the initiation of pharmacological  treatment for hypertension, as well as recommendations on intervals for follow up, target blood  pressure to be achieved for control, and the cadre of health care workers who may initiate treatment.  The guideline provides the basis for deciding whether to initiate treatment with monotherapy, dual  therapy or single-pill combinations, as well as guidance for countries selecting medicines and algorithms  for hypertension control for their national guidelines for hypertension management. The guideline was developed in accordance with the WHO Handbook for Guideline Development. In  brief, the WHO Steering Group, in collaboration with the Guideline Development Group, developed  key questions and rated outcomes to identify those critical for the development of the guideline.  Conflicts of interest were handled in line with the current Compliance, Risk Management and Ethics  (CRE) policy and all members of the GDG were asked to fill in the standard WHO Declaration of Interest  (DOI) forms, which were reviewed. An overview of systematic reviews of the evidence was used to build  summary of findings tables according to the Grading of Recommendations, Assessment, Development  and Evaluations (GRADE) approach. The Guideline Development Group developed recommendations,  considering the certainty of the evidence; the balance between desirable and undesirable effects;  resource requirements and cost-effectiveness; health equity; acceptability, patient values and  preferences, and feasibility. Recommendations  1. RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF  PHARMACOLOGICAL TREATMENT WHO recommends initiation of pharmacological antihypertensive treatment of individuals  with a confirmed diagnosis of hypertension and systolic blood pressure of ≥140 mmHg or  diastolic blood pressure of ≥90 mmHg. Strong recommendation, moderate- to high-certainty evidence WHO recommends pharmacological antihypertensive treatment of individuals with existing  cardiovascular disease and systolic blood pressure of 130–139 mmHg. Strong recommendation, moderate- to high-certainty evidence EXECUTIVE SUMMARY...
[4] score=0.2505 | file: file1.pdf | page: 25 | chunk_id=file1.pdf_ch0022
     recommendation.  5. RECOMMENDATION ON COMBINATION THERAPY For adults with hypertension requiring pharmacological treatment, WHO suggests  combination therapy, preferably with a single-pill combination (to improve adherence and  persistence), as an initial treatment. Antihypertensive medications used in combination  therapy should be chosen from the following three drug classes: diuretics (thiazide or  thiazide-like), angiotensin-converting enzyme inhibitors (ACEis)/angiotensin-receptor  blockers (ARBs), and long-acting dihydropyridine calcium channel blockers (CCBs). Conditional recommendation, moderate-certainty evidence Implementation remarks: [ [ Combination medication therapy may be especially valuable when the baseline BP is  ≥20/10 mmHg higher than the target blood pressure. [ [ Single-pill combination therapy improves medication-taking adherence and persistence and BP  control. RECOMMENDATIONS 13...
[5] score=0.2815 | file: file1.pdf | page: 19 | chunk_id=file1.pdf_ch0011

# Relevance Labels (Top-5)

## Config A_600_100

| Question | Rank1 | Rank2 | Rank3 | Rank4 | Rank5 |
|---|---|---|---|---|---|
| Q01 | 1 | 0 | 1 | 0 | 0 |
| Q06 | 1 | 0 | 0 | 0 | 0 |
| Q11 | 0 | 0 | 0 | 0 | 0 |

## Config B_800_200

| Question | Rank1 | Rank2 | Rank3 | Rank4 | Rank5 |
|---|---|---|---|---|---|
| Q01 | 1 | 1 | 0 | 1 | 0 |
| Q06 | 1 | 0 | 0 | 0 | 0 |
| Q11 | 0 | 0 | 0 | 0 | 0 |

## Percision@5 VS. Percision@3

#### Config A_600_100

| Question | Precision@3 | Precision@5 |
|---|---|---|
| Q01 | 0.67 | 0.40 |
| Q06 | 0.33 | 0.20 |
| Q11 | 0.00 | 0.00 |
| **Average** | **0.33** | **0.20** |

#### Config B_800_200

| Question | Precision@3 | Precision@5 |
|---|---|---|
| Q01 | 0.67 | 0.60 |
| Q06 | 0.33 | 0.20 |
| Q11 | 0.00 | 0.00 |
| **Average** | **0.33** | **0.27** |

In [15]:
vectorstore_b.similarity_search_with_score("Under the NICE Step 1 treatment recommendations, what is the correct initial medication for a 60-year-old patient of Black African family origin who does not have type 2 diabetes?", k=15)

[(Document(id='4e436ee7-faa0-411b-87bc-4794261b47be', metadata={'chunk_id': 'file2.pdf_ch0112', 'source_url': './files\\file2.pdf', 'document_name': 'file2.pdf', 'page_number': 43}, page_content='people of Black African or African–Caribbean family origin). The committee discussed the \nevidence for this and agreed that it was sufficient to support and retain this \nrecommendation. The committee agreed it should be broadened to include the choice of \nan ACE inhibitor or an angiotensin\xa0II receptor blocker (ARB; also referred to as A-type \ndrugs), because they are now cost equivalent, and the committee also agreed they are \nclinically equivalent. \nFor people of Black African or African–Caribbean family origin with type\xa02 diabetes, the \nprevious recommendation was to offer step\xa01 dual therapy with an ACE inhibitor and either \na diuretic (D-type drug) or a calcium channel blocker (CCB; C-type drug). However, these \nrecommendations were based on monotherapy studies and when the committee looked at \nthis evidence alongside the new dual therapy evidence review, they concluded that it was \ninsufficient to recommend starting dual therapy in any subgroup of people with type\xa02 \ndiabetes. The committee noted that people with type\xa02 diabetes who are older or are of \nBlack African or African–Caribbean family origin may not achieve their target blood \npressure on ACE inhibitor or ARB monotherapy and may need to start step\xa02 drug therapy \nin the short term. \nHow the recommendations might affect practice \nOverall, the recommendations for step\xa01 treatment reflect current practice for people who \ndo not have type\xa02 diabetes. For people of Black African or African–Caribbean family origin \nwho have type\xa02 diabetes, the recommendation to start antihypertensive monotherapy \nrather than dual therapy may result in an extra clinical appointment if the dose needs to be \nadjusted. However, it may also reduce potential harms from initial overtreatment of blood \npressure. \nReturn to recommendations \nStep 2 and 3 treatment \nRecommendations 1.4.40 to 1.4.45 \nWhy the committee made the recommendations \nNo evidence for step\xa02 or step\xa03 treatment was identified that was relevant to determining \nthe best sequence for step\xa02 and step\xa03 antihypertensive treatment. Some of the studies \n\n.'),
  0.2324594259262085),
 (Document(id='72a80421-6768-4078-a11e-9dfb1461aa28', metadata={'source_url': './files\\file2.pdf', 'document_name': 'file2.pdf', 'chunk_id': 'file2.pdf_ch0111', 'page_number': 42}, page_content="Step 1 treatment \nRecommendations 1.4.32 to 1.4.39 \nWhy the committee made the recommendations \nThe committee reviewed the evidence for starting treatment for primary hypertension with \na single antihypertensive medicine compared with starting with 2\xa0antihypertensive \nmedicines at once (dual therapy). Additionally, the committee reviewed the evidence on \nwhether specific subgroups of people with hypertension might benefit from starting on \ndual therapy, for example people with type\xa02 diabetes, older people, or those of particular \nfamily origins. \nSome limited evidence from a single study showed that initial dual therapy may reduce \ncardiovascular events in people with hypertension and type\xa02 diabetes, but the committee \nmembers were disappointed that more comprehensive data was not available. The \ncommittee discussed the benefits of optimising treatment for hypertension early and \nagreed that this can substantially improve quality of life. However, there was not enough \nevidence to determine confidently the benefits or harms of starting treatment with dual \ntherapy. In response to the lack of available evidence, the committee developed a \nrecommendation for research on step\xa01 treatment to determine if particular subgroups \nwould benefit from starting dual therapy, to inform future guidance. \nIn the absence of compelling new evidence on step\xa01 dual therapy, the committee agreed \nthat the previous recommendations for step\xa01 treatment should be retained (with minor \nchanges for clarity), because they were based on robust clinical and cost-effectiveness \nevidence. One exception to this was the 2006 recommendation for considering betablockers in certain groups of younger people. The committee discussed this \nrecommendation and agreed that beta-blockers are rarely used as step\xa01 antihypertensive \ntreatment in current practice and there is no established relationship between betablocker use in primary hypertension and a reduction in cardiovascular events. For these \nreasons, the committee decided that the recommendation should not be retained. The \ncommittee noted that this is consistent with most international guidelines. \nThis guideline also updates and replaces the section on blood pressure management from \nNICE's guideline on type\xa02 diabetes in adults. That guideline recommended that adults \nwith type\xa02 diabetes of any age should start on an angiotensin-converting enzyme (ACE) \ninhibitor as step\xa01 treatment (except women with a possibility of becoming pregnant and \n\n."),
  0.26647740602493286),
 (Document(id='b2533a9f-a429-4cb4-89e0-f8f1ebcf66fb', metadata={'chunk_id': 'file2.pdf_ch0081', 'document_name': 'file2.pdf', 'page_number': 12, 'source_url': './files\\file2.pdf'}, page_content="For a short explanation of why the committee deleted the recommendation on \nrelaxation therapies and how this might affect practice, see the rationale and impact \nsection on relaxation therapies. \nFull details of the evidence and the committee's discussion are in evidence review H: \nrelaxation therapies. \nStarting antihypertensive drug treatment \nNICE has produced a patient decision aid on treatment options for hypertension to help \npeople and their healthcare professionals discuss the different types of treatment and \nmake a decision that is right for each person. \nFor advice on shared decision making for medicines, see the information on patient \ndecision aids in NICE's guideline on medicines optimisation. \nTo support adherence and ensure that people with hypertension make the most effective \nuse of their medicines, see NICE's guideline on medicines adherence. \n1.4.9 \nOffer antihypertensive drug treatment in addition to lifestyle advice to adults of \nany age with persistent stage\xa02 hypertension. Use clinical judgement for people \nof any age with frailty or multimorbidity (see also NICE's guideline on \nmultimorbidity). [2019] \n1.4.10 \nDiscuss starting antihypertensive drug treatment, in addition to lifestyle advice, \nwith adults aged under\xa080 with persistent stage\xa01 hypertension who have 1 or \nmore of the following: \n• target organ damage \n• established cardiovascular disease \n• renal disease \n• diabetes \n• an estimated 10-year risk of cardiovascular disease of 10% or more. \n\n."),
  0.29493725299835205),
 (Document(id='9f906815-c6f7-448f-83dc-ce00fb861c3d', metadata={'source_url': './files\\file2.pdf', 'page_number': 35, 'chunk_id': 'file2.pdf_ch0104', 'document_name': 'file2.pdf'}, page_content="Some studies investigated the benefits of treating hypertension in people with lower \ncardiovascular risk or people with blood pressure below 140/90\xa0mmHg. However, some of \nthese studies were not directly relevant because they included a high proportion of \nparticipants with chronic kidney disease and previous cardiovascular events. For this \nreason, several studies could not be used to inform the recommendations. For details of \nthese studies see evidence review C: initiating treatment. \nThe committee discussed the lack of evidence to inform a threshold for starting treatment \nin people aged under\xa040. It was agreed that this is an important area for future research \nand the recommendation for research was carried forward from the 2011 guideline (see \nthe recommendation for research on thresholds for interventions in adults aged under 40). \nThe committee agreed that there was no evidence to suggest that thresholds for starting \ntreatment should be different in people with type\xa02 diabetes. The previous \nrecommendations for people with type\xa02 diabetes (in NICE's guideline on type\xa02 diabetes \nin adults) suggested starting antihypertensive drug treatment if lifestyle interventions \nalone did not reduce blood pressure to below 140/80\xa0mmHg or 130/80\xa0mmHg in the \npresence of kidney, cerebrovascular or eye disease. However, this was based on evidence \nfrom 2\xa0small studies in which the participants did not have hypertension. Further evidence \nfor lower treatment thresholds in people with type\xa02 diabetes was limited within this \nreview, with the committee aware of some evidence to suggest that lower blood pressure \nthresholds did not reduce the rate of cardiovascular events in people without additional \nrisk factors. The committee therefore agreed that there was insufficient evidence to \nrecommend a different threshold for starting treatment for this subgroup. \nThere was no evidence identified on thresholds for people aged over\xa080, and no prior \nrecommendation for this age group with hypertension below stage\xa02; therefore, the \ncommittee agreed that the threshold for starting treatment in people aged over\xa080 should \nbe consistent with the target for treatment in this population (150/90\xa0mmHg or lower). \nThe committee discussed the additional risks of starting treatment in older people, \nparticularly those who are frail or have multiple comorbidities. Based on their expertise \nand experience, they agreed that the use of clinical judgement should be highlighted in \ndecision making for people with frailty or multimorbidity, and that it should apply to people \nof any age. The committee agreed that a number of factors should be considered when \ndiscussing treatment options in this group and noted that healthcare professionals should \nrefer to NICE's guideline on multimorbidity for further advice. \n\n."),
  0.29560303688049316),
 (Document(id='5ac51cef-2871-49b6-88e5-dbb87cdb70e5', metadata={'document_name': 'file2.pdf', 'page_number': 51, 'source_url': './files\\file2.pdf', 'chunk_id': 'file2.pdf_ch0120'}, page_content="Update information \nFebruary 2026: We added recommendation 1.2.11 to offer advice on healthy living to \npeople who have raised blood pressure but have not been diagnosed with hypertension. \nNovember 2023: We updated recommendations 1.1.5, 1.1.6 and 1.4.16 and made 2 new \nrecommendations (1.1.7 and 1.1.8) on how to measure and manage postural hypotension \n(see the February 2023 surveillance report). We also added 2 tables to the section on \nmonitoring treatment and blood pressure targets to summarise blood pressure targets in \nthis guideline and NICE's guidelines on type 1 diabetes and chronic kidney disease (see \nthe November 2023 surveillance report). \nMarch\xa02022: We have reviewed the evidence on blood pressure targets for people with \ncardiovascular disease, and made a new recommendation. This is marked [2022]. \nWe have also reassessed the evidence on antihypertensive drug treatment, and made a \nnew recommendation for people with cardiovascular disease. This is marked [2022]. \nFor recommendations ending [2019, amended 2022], we have not reviewed the evidence \nfor people without cardiovascular disease. We have made minor changes to the wording of \nthe recommendations without changing the intent. For an explanation of these changes, \nsee the rationale and impact section on blood pressure targets for people with \ncardiovascular disease. \nAugust\xa02019: We have reviewed the evidence and made new recommendations on \ndiagnosis, monitoring and drug treatment for hypertension, and identifying who to refer for \nsame-day specialist review. These recommendations are marked [2019]. \nWe have also made some changes without an evidence review: \n• the information on cuff size for measuring blood pressure was moved to avoid \nrepetition \n• plasma glucose testing was replaced with glycated haemoglobin (HbA1C) to reflect \ncurrent practice \n• a note was added because of concerns about the risks of salt substitutes in some \n\n."),
  0.2973955273628235),
 (Document(id='6bea0d46-ea72-4c34-adea-8aeb18887cef', metadata={'chunk_id': 'file2.pdf_ch0089', 'page_number': 20, 'source_url': './files\\file2.pdf', 'document_name': 'file2.pdf'}, page_content="treatment who: \n• have type\xa02 diabetes and are of any age or family origin (see also \nrecommendation 1.4.30 for adults of Black African or African–Caribbean \nfamily origin) or \n• are aged under\xa055 but not of Black African or African–Caribbean family origin. \n[2019] \nFollow the MHRA safety advice on ACE inhibitors and angiotensin II receptor \nantagonists: not for use in pregnancy, how to use for breastfeeding and \nclarification on breastfeeding. \n1.4.33 \nIf an ACE inhibitor is not tolerated, for example because of cough, offer an ARB to \ntreat hypertension. [2019] \nFollow the MHRA safety advice on ACE inhibitors and angiotensin II receptor \nantagonists: not for use in pregnancy, how to use for breastfeeding and \nclarification on breastfeeding. \n1.4.34 \nDo not combine an ACE inhibitor with an ARB to treat hypertension. [2019] \n1.4.35 \nOffer a calcium-channel blocker (CCB) to adults starting step\xa01 antihypertensive \ntreatment who: \n• are aged 55\xa0or over and do not have type\xa02 diabetes or \n• are of Black African or African–Caribbean family origin and do not have type\xa02 \ndiabetes (of any age). [2019] \n1.4.36 \nIf a CCB is not tolerated, for example because of oedema, offer a thiazide-like \ndiuretic to treat hypertension. [2019] \n1.4.37 \nIf there is evidence of heart failure, offer a thiazide-like diuretic and follow NICE's \nguideline on chronic heart failure. [2019] \n1.4.38 \nIf starting or changing diuretic treatment for hypertension, offer a thiazide-like \ndiuretic, such as indapamide in preference to a conventional thiazide diuretic \nsuch as bendroflumethiazide or hydrochlorothiazide. [2019] \n\n."),
  0.29784196615219116),
 (Document(id='653c1e78-21e6-4ec4-b07a-a0ae812cf32b', metadata={'document_name': 'file2.pdf', 'chunk_id': 'file2.pdf_ch0090', 'page_number': 21, 'source_url': './files\\file2.pdf'}, page_content="1.4.39 \nFor adults with hypertension already having treatment with bendroflumethiazide \nor hydrochlorothiazide, who have stable, well-controlled blood pressure, continue \nwith their current treatment. [2019] \nFor a short explanation of why the committee made the 2019 recommendations and \nhow they might affect practice, see the rationale and impact section on step\xa01 \ntreatment. \nFull details of the evidence and the committee's discussion are in evidence review E: \nstep\xa01 treatment. \nStep 2 treatment \n1.4.40 \nBefore considering next step treatment for hypertension discuss with the person \nif they are taking their medicine as prescribed and support adherence in line with \nNICE's guideline on medicines adherence. [2019] \n1.4.41 \nIf hypertension is not controlled in adults taking step\xa01 treatment of an ACE \ninhibitor or ARB, offer the choice of 1 of the following drugs in addition to step\xa01 \ntreatment: \n• a CCB or \n• a thiazide-like diuretic. [2019] \n1.4.42 \nIf hypertension is not controlled in adults taking step\xa01 treatment of a CCB, offer \nthe choice of 1 of the following drugs in addition to step\xa01 treatment: \n• an ACE inhibitor or \n• an ARB or \n• a thiazide-like diuretic. [2019] \n1.4.43 \nIf hypertension is not controlled in adults of Black African or African–Caribbean \nfamily origin who do not have type\xa02 diabetes taking step\xa01 treatment, consider \nan ARB, in preference to an ACE inhibitor, in addition to step\xa01 treatment. [2019] \n\n."),
  0.2988514304161072),
 (Document(id='58bcc2a4-9ac3-4178-83f3-d918cb1579f4', metadata={'source_url': './files\\file1.pdf', 'chunk_id': 'file1.pdf_ch0044', 'document_name': 'file1.pdf', 'page_number': 39}, page_content='Fig. 4 An approach for starting treatment not using a single-pill combination (i.e. with monotherapy or \nfree combination therapy)\nPharmacological treatment to be initiated under the following circumstances:\n[\n[\nA diagnosis of HTN has already been made.\n[\n[\nInitiation of pharmacological HTN treatment should start no later than four weeks after diagnosis of HTN. \n[\n[\nIf BP level is high or there is accompanying evidence of end organ damage, initiation of treatment should \nbe started without delay.\n[\n[\nPatient should be counselled about starting medication therapy.\n[\n[\nBasic laboratory testing (electrolytes, creatinine, lipogram, glucose, HbA1C, urine dipstick, and ECG) to \noccur as long as it does not delay treatment. \n[\n[\nA CV risk assessment can be conducted immediately (as long as it does not delay initiation of treatment) \nor at a later visit.\n[\n[\nConsider using diuretics or CCB in patients 65 years or older, or those of African or Afro-Caribbean descent, \nbeta-blockers (BBs) post MI, ACEis/ARBs in those with DM, heart failure or CKD.\nTreat adults with BP ≥140 mmHg or ≥90 \n(SBP ≥130 mmHg for those with CVD, DM, CKD). \nStart with medications from any of the following three classes of pharmacological \nantihypertensive medications as an initial treatment: \n1) thiazide and thiazide-like agents, 2) ACEi/ARB, and 3) long-acting dihydropyridine CCB.\nTreatment targets: <140/90 mmHg \n(SBP <130 mmHg for high-risk patients with CVD, DM, CKD).\nFollow up monthly after initiation or a change in antihypertensive medications \nuntil patient reaches target. \nFollow up every 3–6 months for patients with BP under control.\nIMPLEMENTATION TOOLS\n27'),
  0.30104488134384155),
 (Document(id='dd50d3d0-1118-48fa-9cd8-c0066af485ac', metadata={'document_name': 'file2.pdf', 'chunk_id': 'file2.pdf_ch0082', 'source_url': './files\\file2.pdf', 'page_number': 13}, page_content="Use clinical judgement for people with frailty or multimorbidity (see also \nNICE's guideline on multimorbidity). [2019] \n1.4.11 \nDiscuss with the person their individual cardiovascular disease risk and their \npreferences for treatment, including no treatment, and explain the risks and \nbenefits before starting antihypertensive drug treatment. Continue to offer \nlifestyle advice and support them to make lifestyle changes (see the section on \nlifestyle interventions), whether or not they choose to start antihypertensive drug \ntreatment. [2019] \n1.4.12 \nConsider antihypertensive drug treatment in addition to lifestyle advice for adults \naged under\xa060 with stage\xa01 hypertension and an estimated 10-year risk below \n10%. Bear in mind that 10-year cardiovascular risk may underestimate the lifetime \nprobability of developing cardiovascular disease. [2019] \n1.4.13 \nConsider antihypertensive drug treatment in addition to lifestyle advice for \npeople aged over\xa080 with stage\xa01 hypertension if their clinic blood pressure is \nover 150/90\xa0mmHg. Use clinical judgement for people with frailty or \nmultimorbidity (see also NICE's guideline on multimorbidity). [2019] \n1.4.14 \nFor adults aged under\xa040 with hypertension, consider seeking specialist \nevaluation of secondary causes of hypertension and a more detailed assessment \nof the long-term balance of treatment benefit and risks. [2019] \nFor a short explanation of why the committee made the 2019 recommendations and \nhow they might affect practice, see the rationale and impact section on starting \nantihypertensive drug treatment. \nFull details of the evidence and the committee's discussion are in evidence review C: \ninitiating treatment. \nMonitoring treatment and blood pressure targets \nFor specific recommendations on blood pressure control in people with other conditions or \nwho are pregnant, see NICE's guidelines on chronic kidney disease, type 1 diabetes and \n\n."),

### Retrieval Failure Documentation: Q11

| Evaluation Field | Details |
| :--- | :--- |
| **Question (Q11)** | *Under the NICE Step 1 treatment recommendations, what is the correct initial medication for a 60-year-old patient of Black African family origin who does not have type 2 diabetes?* |
| **Failure Mode** | **Correct chunk ranked too low** |
| **Symptom** | The right chunk exists in the database and was retrieved, but it sits at rank 6, missing the top 5 cutoff to be sent to the LLM. The top 5 slots were filled with irrelevant, high-similarity chunks. |
| **Expected Content** | The actionable bullet point on page 20 of `file2.pdf` (chunk `file2.pdf_ch0089`) stating: "Offer a calcium-channel blocker (CCB) to adults starting step 1 antihypertensive treatment who... are aged 55 or over... or are of Black African or African–Caribbean family origin and do not have type 2 diabetes." |
| **Root Cause Analysis** | The semantic search heavily weighted dense narrative paragraphs from the "Rationale and impact" sections (pages 42-43) that repeated the query's keywords ("Step 1 treatment", "type 2 diabetes", "Black African"). This semantic overlap pushed the concise, actionable clinical rule down to position 6. |
| **Mitigation Strategy / Fix** | Apply **reranking** to evaluate the logical context of the top 10-15 results, implement **better chunking** (e.g., separating rationale sections from actionable recommendations), or upgrade to a **stronger embedding model**. |

## Implement reranking

In [16]:
from sentence_transformers import CrossEncoder

cross_encoder = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

In [17]:
def rerank(query, k_final=5, pool_size=15, vs=vectorstore):
    
    candidates = retrieve_topk(query, k=pool_size, vs=vs)
    
    pairs = [[query, doc.page_content] for doc, _ in candidates]
    scores = cross_encoder.predict(pairs)
    
    reranked = sorted(zip(candidates, scores), key=lambda x: x[1], reverse=True)
    return [(doc, rr_score) for ((doc, _), rr_score) in reranked[:k_final]]

In [18]:
q11 = next(x["question"] for x in TEST_QUESTIONS if x["id"] == "Q11")
reranked_results = rerank(q11, k_final=5, pool_size=15, vs=vectorstore_b)

for rank, (doc, score) in enumerate(reranked_results, 1):
    m = doc.metadata
    print(f"[{rank}] rerank_score={score:.4f} p.{m.get('page_number')} chunk_id={m.get('chunk_id')}")
    print(f"     {doc.page_content.replace(chr(10), ' ')}...")

[1] rerank_score=2.9699 p.43 chunk_id=file2.pdf_ch0112
     people of Black African or African–Caribbean family origin). The committee discussed the  evidence for this and agreed that it was sufficient to support and retain this  recommendation. The committee agreed it should be broadened to include the choice of  an ACE inhibitor or an angiotensin II receptor blocker (ARB; also referred to as A-type  drugs), because they are now cost equivalent, and the committee also agreed they are  clinically equivalent.  For people of Black African or African–Caribbean family origin with type 2 diabetes, the  previous recommendation was to offer step 1 dual therapy with an ACE inhibitor and either  a diuretic (D-type drug) or a calcium channel blocker (CCB; C-type drug). However, these  recommendations were based on monotherapy studies and when the committee looked at  this evidence alongside the new dual therapy evidence review, they concluded that it was  insufficient to recommend starting dual therapy in any subgroup of people with type 2  diabetes. The committee noted that people with type 2 diabetes who are older or are of  Black African or African–Caribbean family origin may not achieve their target blood  pressure on ACE inhibitor or ARB monotherapy and may need to start step 2 drug therapy  in the short term.  How the recommendations might affect practice  Overall, the recommendations for step 1 treatment reflect current practice for people who  do not have type 2 diabetes. For people of Black African or African–Caribbean family origin  who have type 2 diabetes, the recommendation to start antihypertensive monotherapy  rather than dual therapy may result in an extra clinical appointment if the dose needs to be  adjusted. However, it may also reduce potential harms from initial overtreatment of blood  pressure.  Return to recommendations  Step 2 and 3 treatment  Recommendations 1.4.40 to 1.4.45  Why the committee made the recommendations  No evidence for step 2 or step 3 treatment was identified that was relevant to determining  the best sequence for step 2 and step 3 antihypertensive treatment. Some of the studies   ....
[2] rerank_score=2.9185 p.21 chunk_id=file2.pdf_ch0090
     1.4.39  For adults with hypertension already having treatment with bendroflumethiazide  or hydrochlorothiazide, who have stable, well-controlled blood pressure, continue  with their current treatment. [2019]  For a short explanation of why the committee made the 2019 recommendations and  how they might affect practice, see the rationale and impact section on step 1  treatment.  Full details of the evidence and the committee's discussion are in evidence review E:  step 1 treatment.  Step 2 treatment  1.4.40  Before considering next step treatment for hypertension discuss with the person  if they are taking their medicine as prescribed and support adherence in line with  NICE's guideline on medicines adherence. [2019]  1.4.41  If hypertension is not controlled in adults taking step 1 treatment of an ACE  inhibitor or ARB, offer the choice of 1 of the following drugs in addition to step 1  treatment:  • a CCB or  • a thiazide-like diuretic. [2019]  1.4.42  If hypertension is not controlled in adults taking step 1 treatment of a CCB, offer  the choice of 1 of the following drugs in addition to step 1 treatment:  • an ACE inhibitor or  • an ARB or  • a thiazide-like diuretic. [2019]  1.4.43  If hypertension is not controlled in adults of Black African or African–Caribbean  family origin who do not have type 2 diabetes taking step 1 treatment, consider  an ARB, in preference to an ACE inhibitor, in addition to step 1 treatment. [2019]   ....
[3] rerank_score=2.4891 p.20 chunk_id=file2.pdf_ch0089
     treatment who:  • have type 2 diabetes and are of any age or family origin (see also  recommendation 1.4.30 for adults of Black African or African–Caribbean  family origin) or  • are aged under 55 but not of Black African or African–Caribbean family origin.  [2019]  Follow the MHRA safety advice on ACE inhibitors and angiotensin II receptor  antagonists: not for use in pregnancy, how to use for breastfeeding and  clarification on breastfeeding.  1.4.33  If an ACE inhibitor is not tolerated, for example because of cough, offer an ARB to  treat hypertension. [2019]  Follow the MHRA safety advice on ACE inhibitors and angiotensin II receptor  antagonists: not for use in pregnancy, how to use for breastfeeding and  clarification on breastfeeding.  1.4.34  Do not combine an ACE inhibitor with an ARB to treat hypertension. [2019]  1.4.35  Offer a calcium-channel blocker (CCB) to adults starting step 1 antihypertensive  treatment who:  • are aged 55 or over and do not have type 2 diabetes or  • are of Black African or African–Caribbean family origin and do not have type 2  diabetes (of any age). [2019]  1.4.36  If a CCB is not tolerated, for example because of oedema, offer a thiazide-like  diuretic to treat hypertension. [2019]  1.4.37  If there is evidence of heart failure, offer a thiazide-like diuretic and follow NICE's  guideline on chronic heart failure. [2019]  1.4.38  If starting or changing diuretic treatment for hypertension, offer a thiazide-like  diuretic, such as indapamide in preference to a conventional thiazide diuretic  such as bendroflumethiazide or hydrochlorothiazide. [2019]   ....
[4] rerank_score=1.1468 p.22 chunk_id=file2.pdf_ch0091
     Step 3 treatment  1.4.44  Before considering next step treatment for hypertension:  • review the person's medications to ensure they are being taken at the  optimal tolerated doses and  • discuss adherence (see recommendation 1.4.40). [2019]  1.4.45  If hypertension is not controlled in adults taking step 2 treatment, offer a  combination of:  • an ACE inhibitor or ARB (see also recommendation 1.4.30 for people of Black  African or African–Caribbean family origin) and  • a CCB and  • a thiazide-like diuretic. [2019]  For a short explanation of why the committee made the 2019 recommendations and  how they might affect practice, see the rationale and impact section on step 2 and 3  treatment.  Full details of the evidence and the committee's discussion are in evidence review F:  step 2 and step 3 treatment.  Step 4 treatment  1.4.46  If hypertension is not controlled in adults taking the optimal tolerated doses of an  ACE inhibitor or an ARB plus a CCB and a thiazide-like diuretic, regard them as  having resistant hypertension. [2019]  1.4.47  Before considering further treatment for a person with resistant hypertension:  • Confirm elevated clinic blood pressure measurements using ambulatory or  home blood pressure recordings.  • Assess for postural hypotension.   ....
[5] rerank_score=0.6231 p.42 chunk_id=file2.pdf_ch0111
     Step 1 treatment  Recommendations 1.4.32 to 1.4.39  Why the committee made the recommendations  The committee reviewed the evidence for starting treatment for primary hypertension with  a single antihypertensive medicine compared with starting with 2 antihypertensive  medicines at once (dual therapy). Additionally, the committee reviewed the evidence on  whether specific subgroups of people with hypertension might benefit from starting on  dual therapy, for example people with type 2 diabetes, older people, or those of particular  family origins.  Some limited evidence from a single study showed that initial dual therapy may reduce  cardiovascular events in people with hypertension and type 2 diabetes, but the committee  members were disappointed that more comprehensive data was not available. The  committee discussed the benefits of optimising treatment for hypertension early and  agreed that this can substantially improve quality of life. However, there was not enough  evidence to determine confidently the benefits or harms of starting treatment with dual  therapy. In response to the lack of available evidence, the committee developed a  recommendation for research on step 1 treatment to determine if particular subgroups  would benefit from starting dual therapy, to inform future guidance.  In the absence of compelling new evidence on step 1 dual therapy, the committee agreed  that the previous recommendations for step 1 treatment should be retained (with minor  changes for clarity), because they were based on robust clinical and cost-effectiveness  evidence. One exception to this was the 2006 recommendation for considering betablockers in certain groups of younger people. The committee discussed this  recommendation and agreed that beta-blockers are rarely used as step 1 antihypertensive  treatment in current practice and there is no established relationship between betablocker use in primary hypertension and a reduction in cardiovascular events. For these  reasons, the committee decided that the recommendation should not be retained. The  committee noted that this is consistent with most international guidelines.  This guideline also updates and replaces the section on blood pressure management from  NICE's guideline on type 2 diabetes in adults. That guideline recommended that adults  with type 2 diabetes of any age should start on an angiotensin-converting enzyme (ACE)  inhibitor as step 1 treatment (except women with a possibility of becoming pregnant and   ....

## The Result
The Initial Search (The Problem): Your standard vector search was easily tricked by keyword density. The background "Rationale" sections repeated your query's keywords ("Black African," "type 2 diabetes," "Step 1") so often that the system thought they were the best match. This keyword overload pushed the actual, concise clinical rule down to rank 6.

The Reranking (The Fix): The reranker stepped in like a reading comprehension judge. Instead of just matching concepts, it evaluated the logical relationship between your exact question and the text. It recognized that the chunk on page 20 actually provided the actionable answer to your specific conditions (especially the "does not have type 2 diabetes" part), successfully bumping it up into your top 3 results.

In [19]:
retrieve_topk(TEST_QUESTIONS[1]["question"], 17, vs=vectorstore_b)

[(Document(id='a5d70c2a-bf9d-40ec-b859-53b173e5ff04', metadata={'chunk_id': 'file2.pdf_ch0094', 'source_url': './files\\file2.pdf', 'page_number': 25, 'document_name': 'file2.pdf'}, page_content='Terms used in this guideline \nThis section defines terms that have been used in a particular way for this guideline. For \nother definitions see the NICE glossary. \nAccelerated hypertension \nA severe increase in blood pressure to 180/120\xa0mmHg or higher (and often over 220/\n120\xa0mmHg) with signs of retinal haemorrhage and/or papilloedema (swelling of the optic \nnerve). It is usually associated with new or progressive target organ damage and is also \nknown as malignant hypertension. \nEstablished cardiovascular disease \nMedical history of ischaemic heart disease, cerebrovascular disease, peripheral vascular \ndisease, aortic aneurysm or heart failure. Cardiovascular disease is a general term for \nconditions affecting the heart or blood vessels. It is usually associated with a build-up of \nfatty deposits inside the arteries (atherosclerosis) and an increased risk of blood clots. It \ncan also be associated with damage to arteries in organs such as the brain, heart, kidneys \nand eyes through deposition of glassy material within the artery walls (arteriosclerosis). \nCardiovascular disease is 1 of the main causes of death and disability in the UK, but it can \noften largely be prevented by leading a healthy lifestyle. \nMasked hypertension \nClinic blood pressure measurements are normal (less than 140/90\xa0mmHg), but blood \npressure measurements are higher when taken outside the clinic using average daytime \nambulatory blood pressure monitoring (ABPM) or average home blood pressure monitoring \n(HBPM) blood pressure measurements. \nPersistent hypertension \nHigh blood pressure at repeated clinical encounters. \nStage\xa01 hypertension \nClinic blood pressure ranging from 140/90\xa0mmHg to 159/99\xa0mmHg and subsequent ABPM \n\n.'),
  0.21286779642105103),
 (Document(id='fc810d0d-b44f-4beb-8697-9afb36ae39ba', metadata={'source_url': './files\\file2.pdf', 'page_number': 4, 'chunk_id': 'file2.pdf_ch0073', 'document_name': 'file2.pdf'}, page_content='This guideline replaces CG127. \nThis guideline partially replaces NG28. \nThis guideline is the basis of QS181, QS28 and QS209. \nOverview \nThis guideline covers identifying and treating primary hypertension (high blood pressure) \nin people aged 18\xa0and over, including people with type\xa02 diabetes. It aims to reduce the \nrisk of cardiovascular problems such as heart attacks and strokes by helping healthcare \nprofessionals to diagnose hypertension accurately and treat it effectively. \nNICE has also produced a guideline on hypertension in pregnancy. \nWho is it for? \n• Healthcare professionals \n• Commissioners and providers \n• People who have or may have high blood pressure, their families and carers \n\n.'),
  0.27738064527511597),
 (Document(id='d6dd9909-28f6-4557-b831-62d1bf3b9130', metadata={'document_name': 'file2.pdf', 'chunk_id': 'file2.pdf_ch0118', 'source_url': './files\\file2.pdf', 'page_number': 49}, page_content='blood pressure (accelerated hypertension) to refer for immediate assessment. The \navailable evidence was reviewed and new recommendations made to provide guidance for \nprimary care on when to refer. \n\n.'),
  0.27817463874816895),
 (Document(id='b973768b-a9e6-4a1e-9319-c744d92d5486', metadata={'document_name': 'file2.pdf', 'chunk_id': 'file2.pdf_ch0116', 'source_url': './files\\file2.pdf', 'page_number': 47}, page_content='How the recommendations might affect practice \nThe emergency symptoms listed in the recommendation may lead to more referrals to \nhospital. However, people with emergency symptoms will benefit from urgent treatment \nbecause accelerated hypertension can be fatal if untreated. \nThere may be some additional resource use from doing target organ damage tests more \nquickly and re-measuring blood pressure within 7\xa0days. However, the number of people \nstarted on treatment immediately may be reduced because of undertaking investigations \nfirst. \nThe population with severe hypertension is very small, and the proportion with severe \nhypertension and additional symptoms that suggest accelerated hypertension is even \nsmaller; therefore, resource impact is unlikely to be substantial. \nReturn to recommendations \n\n.'),
  0.2800566554069519),
 (Document(id='736cc684-5cab-4d43-a8b1-072bc2605667', metadata={'page_number': 52, 'source_url': './files\\file2.pdf', 'chunk_id': 'file2.pdf_ch0121', 'document_name': 'file2.pdf'}, page_content="groups \n• the information on when to refer to the hypertension in pregnancy guideline was made \nclearer. \nThese recommendations are marked [2004, amended 2019] or [2011, amended 2019]. \nRecommendations marked [2004], [2006], [2008], [2009] and [2011] last had an \nevidence review in that year. In some cases minor changes have been made to the \nwording to bring the language and style up to date, without changing the meaning. \nRecommendations\xa01.2.12 and 1.4.24 (marked [2009]) were originally published in \nsection\xa01.4 of NICE's guideline on type\xa02 diabetes in adults, which was updated by this \nguideline. \nMinor changes since publication \nJune 2024: We corrected recommendation 1.4.26 to read 'antihypertensive' instead of \n'hypertensive'. \nOctober 2023: We corrected a link to an evidence review. \nJuly 2022: In recommendation 1.5.1 we clarified the options for people with a blood \npressure of 180/120\xa0mmHg or more and no target organ damage. \nNovember\xa02021: We added a link to the blood pressure@home scheme in \nrecommendation\xa01.4.17. \nDecember\xa02019: Recommendation\xa01.4.13 was amended to clarify that it applies to adults \nover\xa080 with stage\xa01 hypertension. We also made changes to introductory text to clarify \nthat recommendations apply to all adults, including those with type\xa02 diabetes, unless \nlinks to other \nISBN: 978-1-4731-9329-1 \n\n."),
  0.28093087673187256),
 (Document(id='5ac51cef-2871-49b6-88e5-dbb87cdb70e5', metadata={'page_number': 51, 'chunk_id': 'file2.pdf_ch0120', 'document_name': 'file2.pdf', 'source_url': './files\\file2.pdf'}, page_content="Update information \nFebruary 2026: We added recommendation 1.2.11 to offer advice on healthy living to \npeople who have raised blood pressure but have not been diagnosed with hypertension. \nNovember 2023: We updated recommendations 1.1.5, 1.1.6 and 1.4.16 and made 2 new \nrecommendations (1.1.7 and 1.1.8) on how to measure and manage postural hypotension \n(see the February 2023 surveillance report). We also added 2 tables to the section on \nmonitoring treatment and blood pressure targets to summarise blood pressure targets in \nthis guideline and NICE's guidelines on type 1 diabetes and chronic kidney disease (see \nthe November 2023 surveillance report). \nMarch\xa02022: We have reviewed the evidence on blood pressure targets for people with \ncardiovascular disease, and made a new recommendation. This is marked [2022]. \nWe have also reassessed the evidence on antihypertensive drug treatment, and made a \nnew recommendation for people with cardiovascular disease. This is marked [2022]. \nFor recommendations ending [2019, amended 2022], we have not reviewed the evidence \nfor people without cardiovascular disease. We have made minor changes to the wording of \nthe recommendations without changing the intent. For an explanation of these changes, \nsee the rationale and impact section on blood pressure targets for people with \ncardiovascular disease. \nAugust\xa02019: We have reviewed the evidence and made new recommendations on \ndiagnosis, monitoring and drug treatment for hypertension, and identifying who to refer for \nsame-day specialist review. These recommendations are marked [2019]. \nWe have also made some changes without an evidence review: \n• the information on cuff size for measuring blood pressure was moved to avoid \nrepetition \n• plasma glucose testing was replaced with glycated haemoglobin (HbA1C) to reflect \ncurrent practice \n• a note was added because of concerns about the risks of salt substitutes in some \n\n."),
  0.28623467683792114),
 (Document(id='b2533a9f-a429-4cb4-89e0-f8f1ebcf66fb', metadata={'document_name': 'file2.pdf', 'source_url': './files\\file2.pdf', 'chunk_id': 'file2.pdf_ch0081', 'page_number': 12}, page_content="For a short explanation of why the committee deleted the recommendation on \nrelaxation therapies and how this might affect practice, see the rationale and impact \nsection on relaxation therapies. \nFull details of the evidence and the committee's discussion are in evidence review H: \nrelaxation therapies. \nStarting antihypertensive drug treatment \nNICE has produced a patient decision aid on treatment options for hypertension to help \npeople and their healthcare professionals discuss the different types of treatment and \nmake a decision that is right for each person. \nFor advice on shared decision making for medicines, see the information on patient \ndecision aids in NICE's guideline on medicines optimisation. \nTo support adherence and ensure that people with hypertension make the most effective \nuse of their medicines, see NICE's guideline on medicines adherence. \n1.4.9 \nOffer antihypertensive drug treatment in addition to lifestyle advice to adults of \nany age with persistent stage\xa02 hypertension. Use clinical judgement for people \nof any age with frailty or multimorbidity (see also NICE's guideline on \nmultimorbidity). [2019] \n1.4.10 \nDiscuss starting antihypertensive drug treatment, in addition to lifestyle advice, \nwith adults aged under\xa080 with persistent stage\xa01 hypertension who have 1 or \nmore of the following: \n• target organ damage \n• established cardiovascular disease \n• renal disease \n• diabetes \n• an estimated 10-year risk of cardiovascular disease of 10% or more. \n\n."),
  0.29427433013916016),
 (Document(id='7b507cb1-50b8-4cf1-934b-8811aed9f02b', metadata={'page_number': 9, 'chunk_id': 'file1.pdf_ch0001', 'source_url': './files\\file1.pdf', 'document_name': 'file1.pdf'}, page_content='Executive summary\nMore people die each year from cardiovascular diseases than from any other cause. Over three \nquarters of heart disease and stroke-related deaths occur in low-income and middle-income countries. \nHypertension – or elevated blood pressure – is a serious medical condition that significantly increases the \nrisk of heart, brain, kidney and other diseases. Hypertension can be defined using specific systolic and \ndiastolic blood pressure levels or reported use of antihypertensive medications. An estimated 1.4 billion \npeople worldwide have high blood pressure, but just 14% have it under control. However, cost-effective \ntreatment options do exist.\nIn this guideline, the World Health Organization (WHO) provides the most current and relevant \nevidence-based global public health guidance on the initiation of treatment with pharmacological \nagents for hypertension in adults. The recommendations target adult, non-pregnant patients who were \nappropriately diagnosed with hypertension and counselled about life-style modifications. \nThe guideline provides new recommendations on the threshold for the initiation of pharmacological \ntreatment for hypertension, as well as recommendations on intervals for follow up, target blood \npressure to be achieved for control, and the cadre of health care workers who may initiate treatment. \nThe guideline provides the basis for deciding whether to initiate treatment with monotherapy, dual \ntherapy or single-pill combinations, as well as guidance for countries selecting medicines and algorithms \nfor hypertension control for their national guidelines for hypertension management.\nThe guideline was developed in accordance with the WHO Handbook for Guideline Development. In \nbrief, the WHO Steering Group, in collaboration with the Guideline Development Group, developed \nkey questions and rated outcomes to identify those critical for the development of the guideline. \nConflicts of interest were handled in line with the current Compliance, Risk Management and Ethics \n(CRE) policy and all members of the GDG were asked to fill in the standard WHO Declaration of Interest \n(DOI) forms, which were reviewed. An overview of systematic reviews of the evidence was used to build \nsummary of findings tables according to the Grading of Recommendations, Assessment, Development \nand Evaluations (GRADE) approach. The Guideline Development Group developed recommendations, \nconsidering the certainty of the evidence; the balance between desirable and undesirable effects; \nresource requirements and cost-effectiveness; health equity; acceptability, patient values and \npreferences, and feasibility.\nRecommendations \n1. RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF \nPHARMACOLOGICAL TREATMENT\nWHO recommends initiation of pharmacological antihypertensive treatment of individuals \nwith a confirmed diagnosis of hypertension and systolic blood pressure of ≥140 mmHg or \ndiastolic blood pressure of ≥90 mmHg.\nStrong recommendation, moderate- to high-certainty evidence\nWHO recommends pharmacological antihypertensive treatment of individuals with existing \ncardiovascular disease and systolic blood pressure of 130–139 mmHg.\nStrong recommendation, moderate- to high-certainty evidence\nEXECUTIVE SUMMARY'),
  0.29835277795791626),
 (Document(id='4f484e7f-a277-4e0f-ac8b-4f1765b5b874', metadata={'document_name': 'file2.pdf', 'source_url': './files\\file2.pdf', 'page_number': 46, 'chunk_id': 'file2.pdf_ch0115'}, page_content='already being done. \nReturn to recommendations \nIdentifying who to refer for same-day specialist \nreview \nRecommendations 1.5.1 to 1.5.3 \nWhy the committee made the recommendations \nThere was no evidence identified to inform recommendations on this topic. The committee \nreviewed the 2011 recommendations and agreed that they should be updated by \nconsensus based on their clinical expertise. In particular they agreed it would be helpful to \nclarify which features warranted same-day referral, which would need further investigation \nand when repeat blood pressure measurement should be taken. \nThe committee noted that it can be difficult to differentiate between accelerated \nhypertension and severe hypertension. They discussed the advantages and \ndisadvantages of broader criteria for same-day referral, which would increase referrals to \nhospital but reduce the risk of missing people who need urgent treatment. The committee \ndecided it would be beneficial to add some emergency symptoms to the existing \nrecommendation, which will help healthcare professionals to decide when to refer. \nBased on their experience, the committee members agreed that some people with severe \nhypertension could be receiving unnecessary treatment because the 2011 guideline \nrecommended treatment based on severe hypertension alone. The committee agreed that \nthis could be prevented if investigations for target organ damage were carried out quickly \nbefore offering treatment in people with severely raised blood pressure and no other \nsymptoms of concern. The committee also agreed that checking blood pressure again \nwithin 7\xa0days in people with no target organ damage would ensure that people with severe \nhypertension are followed up and offered suitable treatment. \nThe committee agreed that further research is needed in this area, particularly for people \nwith extreme hypertension (220/120\xa0mmHg or higher) or emergency symptoms. The \ncommittee members developed a recommendation for research on same-day hospital \nspecialist assessment to help inform future recommendations. \n\n.'),
  0.2988640069961548),
 (Document(id='dd50d3d0-1118-48fa-9cd8-c0066af485ac', metadata={'chunk_id': 'file2.pdf_ch0082', 'source_url': './files\\file2.pdf', 'page_number': 13, 'document_name': 'file2.pdf'}, page_content="Use clinical judgement for people with frailty or multimorbidity (see also \nNICE's guideline on multimorbidity). [2019] \n1.4.11 \nDiscuss with the person their individual cardiovascular disease risk and their \npreferences for treatment, including no treatment, and explain the risks and \nbenefits before starting antihypertensive drug treatment. Continue to offer \nlifestyle advice and support them to make lifestyle changes (see the section on \nlifestyle interventions), whether or not they choose to start antihypertensive drug \ntreatment. [2019] \n1.4.12 \nConsider antihypertensive drug treatment in addition to lifestyle advice for adults \naged under\xa060 with stage\xa01 hypertension and an estimated 10-year risk below \n10%. Bear in mind that 10-year cardiovascular risk may underestimate the lifetime \nprobability of developing cardiovascular disease. [2019] \n1.4.13 \nConsider antihypertensive drug treatment in addition to lifestyle advice for \npeople aged over\xa080 with stage\xa01 hypertension if their clinic blood pressure is \nover 150/90\xa0mmHg. Use clinical judgement for people with frailty or \nmultimorbidity (see also NICE's guideline on multimorbidity). [2019] \n1.4.14 \nFor adults aged under\xa040 with hypertension, consider seeking specialist \nevaluation of secondary causes of hypertension and a more detailed assessment \nof the long-term balance of treatment benefit and risks. [2019] \nFor a short explanation of why the committee made the 2019 recommendations and \nhow they might affect practice, see the rationale and impact section on starting \nantihypertensive drug treatment. \nFull details of the evidence and the committee's discussion are in evidence review C: \ninitiating treatment. \nMonitoring treatment and blood pressure targets \nFor specific recommendations on blood pressure control in people with other conditions or \nwho are pregnant, see NICE's guidelines on chronic kidney disease, type 1 diabetes and \n\n."),
  0.3035391569137573),

In [20]:
from typing import List, Dict

def crossencoder_label(
    expected_answer: str,
    chunk: str,
    threshold: float = 1.0
) -> bool:

    score = cross_encoder.predict(
        [(expected_answer, chunk)]
    )

    return float(score[0]) >= threshold


def label_all_chunks(
    expected_answer: str,
    chunks: List[str],
    threshold: float = 1.0
) -> List[Dict]:

    if not expected_answer or not expected_answer.strip():
        raise ValueError("expected_answer cannot be empty.")

    if not chunks:
        return []

    valid_chunks = [
        chunk for chunk in chunks
        if chunk and chunk.strip()
    ]

    if not valid_chunks:
        return []


    pairs = [
        (expected_answer, chunk)
        for chunk in valid_chunks
    ]

    scores = cross_encoder.predict(pairs)

    results = []

    for chunk, score in zip(valid_chunks, scores):
        score = float(score)

        results.append({
            "chunk": chunk,
            "score": score,
            "relevant": score >= threshold
        })

    return results





expected_answer = TEST_QUESTIONS[1]["expected_answer"]
chunks = [doc.page_content for doc in vectorstore_b.similarity_search(TEST_QUESTIONS[1]["question"],k=30)]

results = label_all_chunks(
    expected_answer=expected_answer,
    chunks=chunks,
    threshold=1.0
)


# Display results
for i, result in enumerate(results, start=1):
    print(f"\n{'=' * 70}")
    print(f"Chunk {i}")
    print(f"Score:     {result['score']:.4f}")
    print(f"Relevant:  {result['relevant']}")
    # print(f"Text:      {result['chunk']}")

======================================================================
Chunk 1
Score:     8.0988
Relevant:  True

======================================================================
Chunk 2
Score:     -9.9059
Relevant:  False

======================================================================
Chunk 3
Score:     -8.2277
Relevant:  False

======================================================================
Chunk 4
Score:     -8.5113
Relevant:  False

======================================================================
Chunk 5
Score:     -7.8747
Relevant:  False

======================================================================
Chunk 6
Score:     -7.9704
Relevant:  False

======================================================================
Chunk 7
Score:     -11.0252
Relevant:  False

======================================================================
Chunk 8
Score:     -7.0420
Relevant:  False

======================================================================
Chunk 9
Score:     -1.2765
Relevant:  False

======================================================================
Chunk 10
Score:     -9.7018
Relevant:  False

======================================================================
Chunk 11
Score:     -5.1790
Relevant:  False

======================================================================
Chunk 12
Score:     -7.8863
Relevant:  False

======================================================================
Chunk 13
Score:     -9.1765
Relevant:  False

======================================================================
Chunk 14
Score:     -9.9225
Relevant:  False

======================================================================
Chunk 15
Score:     -10.0890
Relevant:  False

======================================================================
Chunk 16
Score:     -10.8835
Relevant:  False

======================================================================
Chunk 17
Score:     2.8196
Relevant:  True

======================================================================
Chunk 18
Score:     -6.5067
Relevant:  False

======================================================================
Chunk 19
Score:     -2.6853
Relevant:  False

======================================================================
Chunk 20
Score:     -8.7898
Relevant:  False

======================================================================
Chunk 21
Score:     -9.2766
Relevant:  False

======================================================================
Chunk 22
Score:     -5.5729
Relevant:  False

======================================================================
Chunk 23
Score:     -7.7693
Relevant:  False

======================================================================
Chunk 24
Score:     -5.8912
Relevant:  False

======================================================================
Chunk 25
Score:     -4.3074
Relevant:  False

======================================================================
Chunk 26
Score:     -7.9814
Relevant:  False

======================================================================
Chunk 27
Score:     -2.9757
Relevant:  False

======================================================================
Chunk 28
Score:     -6.9458
Relevant:  False

======================================================================
Chunk 29
Score:     -9.4483
Relevant:  False

======================================================================
Chunk 30
Score:     -9.1680
Relevant:  False

In [21]:
from typing import List, Dict

def crossencoder_label(
    expected_answer: str,
    chunk: str,
    threshold: float = 1.0
) -> bool:
    """Return True when the chunk is relevant to the expected answer."""
    score = cross_encoder.predict([(expected_answer, chunk)])
    return float(score[0]) >= threshold


def label_all_chunks(
    expected_answer: str,
    chunks: List[str],
    threshold: float = 1.0
) -> List[Dict]:
    """
    Evaluate and label all retrieved chunks.
    Returns a list containing the chunk, Cross-Encoder score,
    and relevance label.
    """
    if not expected_answer or not expected_answer.strip():
        raise ValueError("expected_answer cannot be empty.")

    if not chunks:
        return []

    valid_chunks = [chunk for chunk in chunks if chunk and chunk.strip()]

    if not valid_chunks:
        return []

    pairs = [(expected_answer, chunk) for chunk in valid_chunks]
    scores = cross_encoder.predict(pairs)

    results = []
    for chunk, score in zip(valid_chunks, scores):
        score = float(score)
        results.append({
            "chunk": chunk,
            "score": score,
            "relevant": score >= threshold,
        })

    return results

In [22]:
def precision_at_k(relevant_labels: List[bool], k: int) -> float:
    """Compute Precision@K from a list of boolean relevance labels."""
    top_k = relevant_labels[:k]
    if len(top_k) == 0:
        return 0.0
    return sum(top_k) / len(top_k)

def recall_at_k(relevant_in_topk: int, total_relevant: int) -> float:
    if total_relevant == 0:
        return 0.0
    return min(relevant_in_topk, total_relevant) / total_relevant

def f1_at_k(precision: float, recall: float) -> float:
    if precision + recall == 0:
        return 0.0
    return 2 * (precision * recall) / (precision + recall)

def count_total_relevant(expected_answer: str, vectorstore, threshold: float = 1.0) -> int:
    all_docs = vectorstore.get()
    all_chunks = all_docs["documents"]
    labeled = label_all_chunks(expected_answer, all_chunks, threshold)
    return sum(1 for r in labeled if r["relevant"])

In [34]:
from itertools import product

K_VALUES = [3, 5, 7]
CONFIG_NAMES = ["A_600_100", "B_800_200", "C_900_150", "D_400_50"]
THRESHOLD = 1.0  # Cross-Encoder relevance threshold

VECTORSTORES = {
    "A_600_100": vectorstore_a,
    "B_800_200": vectorstore_b,
    "C_900_150": vectorstore_c,
    "D_400_50": vectorstore_d
}

print(f"Grid Search Configuration:")
print(f"  k values:       {K_VALUES}")
print(f"  Configs:        {CONFIG_NAMES}")
print(f"  Questions:      {len(TEST_QUESTIONS)}")
print(f"  Threshold:      {THRESHOLD}")
print(f"  Combinations:   {len(K_VALUES) * len(CONFIG_NAMES)}")

Grid Search Configuration:
  k values:       [3, 5, 7]
  Configs:        ['A_600_100', 'B_800_200', 'C_900_150', 'D_400_50']
  Questions:      15
  Threshold:      1.0
  Combinations:   12

In [35]:
# Precompute total relevant counts once per (config, question)
TOTAL_RELEVANT_CACHE = {}

for config_name in CONFIG_NAMES:
    vs = VECTORSTORES[config_name]
    TOTAL_RELEVANT_CACHE[config_name] = {}

    print(f"\nPrecomputing total relevant for config: {config_name}")
    for q in TEST_QUESTIONS:
        qid = q["id"]
        expected_answer = q["expected_answer"]

        total_rel = count_total_relevant(expected_answer, vs, THRESHOLD)
        TOTAL_RELEVANT_CACHE[config_name][qid] = total_rel

        print(f"  {qid}: total_relevant={total_rel}")

print("\nTotal relevant cache ready.")

Precomputing total relevant for config: A_600_100
  Q01: total_relevant=12
  Q02: total_relevant=3
  Q03: total_relevant=1
  Q04: total_relevant=2
  Q05: total_relevant=3
  Q06: total_relevant=1
  Q07: total_relevant=4
  Q08: total_relevant=2
  Q09: total_relevant=9
  Q10: total_relevant=7
  Q11: total_relevant=2
  Q12: total_relevant=3
  Q13: total_relevant=1
  Q14: total_relevant=4
  Q15: total_relevant=1

Precomputing total relevant for config: B_800_200
  Q01: total_relevant=10
  Q02: total_relevant=3
  Q03: total_relevant=1
  Q04: total_relevant=1
  Q05: total_relevant=3
  Q06: total_relevant=1
  Q07: total_relevant=5
  Q08: total_relevant=2
  Q09: total_relevant=8
  Q10: total_relevant=7
  Q11: total_relevant=5
  Q12: total_relevant=2
  Q13: total_relevant=1
  Q14: total_relevant=3
  Q15: total_relevant=1

Precomputing total relevant for config: C_900_150
  Q01: total_relevant=8
  Q02: total_relevant=3
  Q03: total_relevant=1
  Q04: total_relevant=2
  Q05: total_relevant=3
  Q06: total_relevant=1
  Q07: total_relevant=3
  Q08: total_relevant=2
  Q09: total_relevant=8
  Q10: total_relevant=7
  Q11: total_relevant=2
  Q12: total_relevant=2
  Q13: total_relevant=1
  Q14: total_relevant=2
  Q15: total_relevant=1

Precomputing total relevant for config: D_400_50
  Q01: total_relevant=17
  Q02: total_relevant=3
  Q03: total_relevant=1
  Q04: total_relevant=2
  Q05: total_relevant=5
  Q06: total_relevant=1
  Q07: total_relevant=8
  Q08: total_relevant=1
  Q09: total_relevant=13
  Q10: total_relevant=10
  Q11: total_relevant=6
  Q12: total_relevant=4
  Q13: total_relevant=1
  Q14: total_relevant=2
  Q15: total_relevant=1

Total relevant cache ready.

In [36]:
import pandas as pd

all_rows = []
grid_results = []

for config_name, k in product(CONFIG_NAMES, K_VALUES):
    vs = VECTORSTORES[config_name]
    precisions = []
    recalls = []
    f1s = []

    print(f"\n{'─' * 70}")
    print(f"Config: {config_name} | k={k}")
    print(f"{'─' * 70}")

    for q in TEST_QUESTIONS:
        qid = q["id"]
        question = q["question"]
        expected_answer = q["expected_answer"]

        # docs = vs.similarity_search(question, k=k)
        docs = [doc[0] for doc in rerank(question, k_final=k, pool_size=40, vs=vs)]
        chunks = [doc.page_content for doc in docs]

        labeled = label_all_chunks(
            expected_answer=expected_answer,
            chunks=chunks,
            threshold=THRESHOLD,
        )

        relevance_labels = [r["relevant"] for r in labeled]

        p_at_k = precision_at_k(relevance_labels, k)

        total_rel = TOTAL_RELEVANT_CACHE[config_name][qid]
        r_at_k = recall_at_k(sum(relevance_labels), total_rel)
        f1_k = f1_at_k(p_at_k, r_at_k)

        precisions.append(p_at_k)
        recalls.append(r_at_k)
        f1s.append(f1_k)

        chunk_scores = [r["score"] for r in labeled]
        chunk_relevance = [r["relevant"] for r in labeled]

        print(f"  {qid}: P@{k}={p_at_k:.4f}  R@{k}={r_at_k:.4f}  F1@{k}={f1_k:.4f}  "
              f"[relevant: {sum(chunk_relevance)}/{len(chunk_relevance)}, total_rel: {total_rel}]")

        all_rows.append({
            "config": config_name,
            "k": k,
            "question_id": qid,
            "question_level": q["level"],
            "question_source": q["source"],
            "precision_at_k": p_at_k,
            "recall_at_k": r_at_k,
            "f1_at_k": f1_k,
            "num_relevant": sum(chunk_relevance),
            "total_relevant": total_rel,
            "num_retrieved": len(chunk_relevance),
            "chunk_scores": chunk_scores,
            "chunk_relevance": chunk_relevance,
        })

    mean_p = sum(precisions) / len(precisions)
    mean_r = sum(recalls) / len(recalls)
    mean_f1 = sum(f1s) / len(f1s)

    grid_results.append({
        "config": config_name,
        "k": k,
        "mean_precision_at_k": mean_p,
        "mean_recall_at_k": mean_r,
        "mean_f1_at_k": mean_f1,
        "std_precision_at_k": pd.Series(precisions).std(),
        "min_precision_at_k": min(precisions),
        "max_precision_at_k": max(precisions),
    })

    print(f"\n  ► {config_name} k={k}:  "
          f"Mean P@{k}={mean_p:.4f}  "
          f"Mean R@{k}={mean_r:.4f}  "
          f"Mean F1@{k}={mean_f1:.4f}")

print("\nGrid search complete!")

──────────────────────────────────────────────────────────────────────
Config: A_600_100 | k=3
──────────────────────────────────────────────────────────────────────
  Q01: P@3=1.0000  R@3=0.2500  F1@3=0.4000  [relevant: 3/3, total_rel: 12]
  Q02: P@3=0.3333  R@3=0.3333  F1@3=0.3333  [relevant: 1/3, total_rel: 3]
  Q03: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q04: P@3=0.3333  R@3=0.5000  F1@3=0.4000  [relevant: 1/3, total_rel: 2]
  Q05: P@3=0.0000  R@3=0.0000  F1@3=0.0000  [relevant: 0/3, total_rel: 3]
  Q06: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q07: P@3=0.3333  R@3=0.2500  F1@3=0.2857  [relevant: 1/3, total_rel: 4]
  Q08: P@3=0.0000  R@3=0.0000  F1@3=0.0000  [relevant: 0/3, total_rel: 2]
  Q09: P@3=1.0000  R@3=0.3333  F1@3=0.5000  [relevant: 3/3, total_rel: 9]
  Q10: P@3=1.0000  R@3=0.4286  F1@3=0.6000  [relevant: 3/3, total_rel: 7]
  Q11: P@3=0.3333  R@3=0.5000  F1@3=0.4000  [relevant: 1/3, total_rel: 2]
  Q12: P@3=0.6667  R@3=0.6667  F1@3=0.6667  [relevant: 2/3, total_rel: 3]
  Q13: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q14: P@3=0.6667  R@3=0.5000  F1@3=0.5714  [relevant: 2/3, total_rel: 4]
  Q15: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]

  ► A_600_100 k=3:  Mean P@3=0.4667  Mean R@3=0.5175  Mean F1@3=0.4105

──────────────────────────────────────────────────────────────────────
Config: A_600_100 | k=5
──────────────────────────────────────────────────────────────────────
  Q01: P@5=0.6000  R@5=0.2500  F1@5=0.3529  [relevant: 3/5, total_rel: 12]
  Q02: P@5=0.2000  R@5=0.3333  F1@5=0.2500  [relevant: 1/5, total_rel: 3]
  Q03: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q04: P@5=0.2000  R@5=0.5000  F1@5=0.2857  [relevant: 1/5, total_rel: 2]
  Q05: P@5=0.0000  R@5=0.0000  F1@5=0.0000  [relevant: 0/5, total_rel: 3]
  Q06: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q07: P@5=0.2000  R@5=0.2500  F1@5=0.2222  [relevant: 1/5, total_rel: 4]
  Q08: P@5=0.2000  R@5=0.5000  F1@5=0.2857  [relevant: 1/5, total_rel: 2]
  Q09: P@5=1.0000  R@5=0.5556  F1@5=0.7143  [relevant: 5/5, total_rel: 9]
  Q10: P@5=0.8000  R@5=0.5714  F1@5=0.6667  [relevant: 4/5, total_rel: 7]
  Q11: P@5=0.2000  R@5=0.5000  F1@5=0.2857  [relevant: 1/5, total_rel: 2]
  Q12: P@5=0.4000  R@5=0.6667  F1@5=0.5000  [relevant: 2/5, total_rel: 3]
  Q13: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q14: P@5=0.4000  R@5=0.5000  F1@5=0.4444  [relevant: 2/5, total_rel: 4]
  Q15: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]

  ► A_600_100 k=5:  Mean P@5=0.3333  Mean R@5=0.5751  Mean F1@5=0.3561

──────────────────────────────────────────────────────────────────────
Config: A_600_100 | k=7
──────────────────────────────────────────────────────────────────────
  Q01: P@7=0.4286  R@7=0.2500  F1@7=0.3158  [relevant: 3/7, total_rel: 12]
  Q02: P@7=0.1429  R@7=0.3333  F1@7=0.2000  [relevant: 1/7, total_rel: 3]
  Q03: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q04: P@7=0.2857  R@7=1.0000  F1@7=0.4444  [relevant: 2/7, total_rel: 2]
  Q05: P@7=0.0000  R@7=0.0000  F1@7=0.0000  [relevant: 0/7, total_rel: 3]
  Q06: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q07: P@7=0.4286  R@7=0.7500  F1@7=0.5455  [relevant: 3/7, total_rel: 4]
  Q08: P@7=0.1429  R@7=0.5000  F1@7=0.2222  [relevant: 1/7, total_rel: 2]
  Q09: P@7=0.8571  R@7=0.6667  F1@7=0.7500  [relevant: 6/7, total_rel: 9]
  Q10: P@7=0.7143  R@7=0.7143  F1@7=0.7143  [relevant: 5/7, total_rel: 7]
  Q11: P@7=0.1429  R@7=0.5000  F1@7=0.2222  [relevant: 1/7, total_rel: 2]
  Q12: P@7=0.2857  R@7=0.6667  F1@7=0.4000  [relevant: 2/7, total_rel: 3]
  Q13: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q14: P@7=0.4286  R@7=0.7500  F1@7=0.5455  [relevant: 3/7, total_rel: 4]
  Q15: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]

  ► A_600_100 k=7:  Mean P@7=0.2952  Mean R@7=0.6754  Mean F1@7=0.3573

──────────────────────────────────────────────────────────────────────
Config: B_800_200 | k=3
──────────────────────────────────────────────────────────────────────
  Q01: P@3=1.0000  R@3=0.3000  F1@3=0.4615  [relevant: 3/3, total_rel: 10]
  Q02: P@3=0.3333  R@3=0.3333  F1@3=0.3333  [relevant: 1/3, total_rel: 3]
  Q03: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q04: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q05: P@3=0.0000  R@3=0.0000  F1@3=0.0000  [relevant: 0/3, total_rel: 3]
  Q06: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q07: P@3=0.3333  R@3=0.2000  F1@3=0.2500  [relevant: 1/3, total_rel: 5]
  Q08: P@3=0.0000  R@3=0.0000  F1@3=0.0000  [relevant: 0/3, total_rel: 2]
  Q09: P@3=1.0000  R@3=0.3750  F1@3=0.5455  [relevant: 3/3, total_rel: 8]
  Q10: P@3=1.0000  R@3=0.4286  F1@3=0.6000  [relevant: 3/3, total_rel: 7]
  Q11: P@3=0.3333  R@3=0.2000  F1@3=0.2500  [relevant: 1/3, total_rel: 5]
  Q12: P@3=0.6667  R@3=1.0000  F1@3=0.8000  [relevant: 2/3, total_rel: 2]
  Q13: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q14: P@3=0.3333  R@3=0.3333  F1@3=0.3333  [relevant: 1/3, total_rel: 3]
  Q15: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]

  ► B_800_200 k=3:  Mean P@3=0.4444  Mean R@3=0.5447  Mean F1@3=0.4049

──────────────────────────────────────────────────────────────────────
Config: B_800_200 | k=5
──────────────────────────────────────────────────────────────────────
  Q01: P@5=0.8000  R@5=0.4000  F1@5=0.5333  [relevant: 4/5, total_rel: 10]
  Q02: P@5=0.2000  R@5=0.3333  F1@5=0.2500  [relevant: 1/5, total_rel: 3]
  Q03: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q04: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q05: P@5=0.0000  R@5=0.0000  F1@5=0.0000  [relevant: 0/5, total_rel: 3]
  Q06: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q07: P@5=0.4000  R@5=0.4000  F1@5=0.4000  [relevant: 2/5, total_rel: 5]
  Q08: P@5=0.2000  R@5=0.5000  F1@5=0.2857  [relevant: 1/5, total_rel: 2]
  Q09: P@5=1.0000  R@5=0.6250  F1@5=0.7692  [relevant: 5/5, total_rel: 8]
  Q10: P@5=0.8000  R@5=0.5714  F1@5=0.6667  [relevant: 4/5, total_rel: 7]
  Q11: P@5=0.2000  R@5=0.2000  F1@5=0.2000  [relevant: 1/5, total_rel: 5]
  Q12: P@5=0.4000  R@5=1.0000  F1@5=0.5714  [relevant: 2/5, total_rel: 2]
  Q13: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q14: P@5=0.4000  R@5=0.6667  F1@5=0.5000  [relevant: 2/5, total_rel: 3]
  Q15: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]

  ► B_800_200 k=5:  Mean P@5=0.3600  Mean R@5=0.6464  Mean F1@5=0.3895

──────────────────────────────────────────────────────────────────────
Config: B_800_200 | k=7
──────────────────────────────────────────────────────────────────────
  Q01: P@7=0.5714  R@7=0.4000  F1@7=0.4706  [relevant: 4/7, total_rel: 10]
  Q02: P@7=0.1429  R@7=0.3333  F1@7=0.2000  [relevant: 1/7, total_rel: 3]
  Q03: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q04: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q05: P@7=0.0000  R@7=0.0000  F1@7=0.0000  [relevant: 0/7, total_rel: 3]
  Q06: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q07: P@7=0.4286  R@7=0.6000  F1@7=0.5000  [relevant: 3/7, total_rel: 5]
  Q08: P@7=0.1429  R@7=0.5000  F1@7=0.2222  [relevant: 1/7, total_rel: 2]
  Q09: P@7=0.8571  R@7=0.7500  F1@7=0.8000  [relevant: 6/7, total_rel: 8]
  Q10: P@7=0.7143  R@7=0.7143  F1@7=0.7143  [relevant: 5/7, total_rel: 7]
  Q11: P@7=0.2857  R@7=0.4000  F1@7=0.3333  [relevant: 2/7, total_rel: 5]
  Q12: P@7=0.2857  R@7=1.0000  F1@7=0.4444  [relevant: 2/7, total_rel: 2]
  Q13: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q14: P@7=0.4286  R@7=1.0000  F1@7=0.6000  [relevant: 3/7, total_rel: 3]
  Q15: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]

  ► B_800_200 k=7:  Mean P@7=0.3048  Mean R@7=0.7132  Mean F1@7=0.3690

──────────────────────────────────────────────────────────────────────
Config: C_900_150 | k=3
──────────────────────────────────────────────────────────────────────
  Q01: P@3=0.6667  R@3=0.2500  F1@3=0.3636  [relevant: 2/3, total_rel: 8]
  Q02: P@3=0.3333  R@3=0.3333  F1@3=0.3333  [relevant: 1/3, total_rel: 3]
  Q03: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q04: P@3=0.6667  R@3=1.0000  F1@3=0.8000  [relevant: 2/3, total_rel: 2]
  Q05: P@3=0.0000  R@3=0.0000  F1@3=0.0000  [relevant: 0/3, total_rel: 3]
  Q06: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q07: P@3=0.3333  R@3=0.3333  F1@3=0.3333  [relevant: 1/3, total_rel: 3]
  Q08: P@3=0.0000  R@3=0.0000  F1@3=0.0000  [relevant: 0/3, total_rel: 2]
  Q09: P@3=1.0000  R@3=0.3750  F1@3=0.5455  [relevant: 3/3, total_rel: 8]
  Q10: P@3=1.0000  R@3=0.4286  F1@3=0.6000  [relevant: 3/3, total_rel: 7]
  Q11: P@3=0.3333  R@3=0.5000  F1@3=0.4000  [relevant: 1/3, total_rel: 2]
  Q12: P@3=0.6667  R@3=1.0000  F1@3=0.8000  [relevant: 2/3, total_rel: 2]
  Q13: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q14: P@3=0.3333  R@3=0.5000  F1@3=0.4000  [relevant: 1/3, total_rel: 2]
  Q15: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]

  ► C_900_150 k=3:  Mean P@3=0.4444  Mean R@3=0.5813  Mean F1@3=0.4384

──────────────────────────────────────────────────────────────────────
Config: C_900_150 | k=5
──────────────────────────────────────────────────────────────────────
  Q01: P@5=0.4000  R@5=0.2500  F1@5=0.3077  [relevant: 2/5, total_rel: 8]
  Q02: P@5=0.2000  R@5=0.3333  F1@5=0.2500  [relevant: 1/5, total_rel: 3]
  Q03: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q04: P@5=0.4000  R@5=1.0000  F1@5=0.5714  [relevant: 2/5, total_rel: 2]
  Q05: P@5=0.0000  R@5=0.0000  F1@5=0.0000  [relevant: 0/5, total_rel: 3]
  Q06: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q07: P@5=0.4000  R@5=0.6667  F1@5=0.5000  [relevant: 2/5, total_rel: 3]
  Q08: P@5=0.2000  R@5=0.5000  F1@5=0.2857  [relevant: 1/5, total_rel: 2]
  Q09: P@5=1.0000  R@5=0.6250  F1@5=0.7692  [relevant: 5/5, total_rel: 8]
  Q10: P@5=0.8000  R@5=0.5714  F1@5=0.6667  [relevant: 4/5, total_rel: 7]
  Q11: P@5=0.2000  R@5=0.5000  F1@5=0.2857  [relevant: 1/5, total_rel: 2]
  Q12: P@5=0.4000  R@5=1.0000  F1@5=0.5714  [relevant: 2/5, total_rel: 2]
  Q13: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q14: P@5=0.4000  R@5=1.0000  F1@5=0.5714  [relevant: 2/5, total_rel: 2]
  Q15: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]

  ► C_900_150 k=5:  Mean P@5=0.3467  Mean R@5=0.6964  Mean F1@5=0.4075

──────────────────────────────────────────────────────────────────────
Config: C_900_150 | k=7
──────────────────────────────────────────────────────────────────────
  Q01: P@7=0.2857  R@7=0.2500  F1@7=0.2667  [relevant: 2/7, total_rel: 8]
  Q02: P@7=0.1429  R@7=0.3333  F1@7=0.2000  [relevant: 1/7, total_rel: 3]
  Q03: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q04: P@7=0.2857  R@7=1.0000  F1@7=0.4444  [relevant: 2/7, total_rel: 2]
  Q05: P@7=0.0000  R@7=0.0000  F1@7=0.0000  [relevant: 0/7, total_rel: 3]
  Q06: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q07: P@7=0.4286  R@7=1.0000  F1@7=0.6000  [relevant: 3/7, total_rel: 3]
  Q08: P@7=0.1429  R@7=0.5000  F1@7=0.2222  [relevant: 1/7, total_rel: 2]
  Q09: P@7=0.8571  R@7=0.7500  F1@7=0.8000  [relevant: 6/7, total_rel: 8]
  Q10: P@7=0.7143  R@7=0.7143  F1@7=0.7143  [relevant: 5/7, total_rel: 7]
  Q11: P@7=0.1429  R@7=0.5000  F1@7=0.2222  [relevant: 1/7, total_rel: 2]
  Q12: P@7=0.2857  R@7=1.0000  F1@7=0.4444  [relevant: 2/7, total_rel: 2]
  Q13: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q14: P@7=0.2857  R@7=1.0000  F1@7=0.4444  [relevant: 2/7, total_rel: 2]
  Q15: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]

  ► C_900_150 k=7:  Mean P@7=0.2762  Mean R@7=0.7365  Mean F1@7=0.3572

──────────────────────────────────────────────────────────────────────
Config: D_400_50 | k=3
──────────────────────────────────────────────────────────────────────
  Q01: P@3=1.0000  R@3=0.1765  F1@3=0.3000  [relevant: 3/3, total_rel: 17]
  Q02: P@3=0.3333  R@3=0.3333  F1@3=0.3333  [relevant: 1/3, total_rel: 3]
  Q03: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q04: P@3=0.3333  R@3=0.5000  F1@3=0.4000  [relevant: 1/3, total_rel: 2]
  Q05: P@3=0.0000  R@3=0.0000  F1@3=0.0000  [relevant: 0/3, total_rel: 5]
  Q06: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q07: P@3=0.6667  R@3=0.2500  F1@3=0.3636  [relevant: 2/3, total_rel: 8]
  Q08: P@3=0.0000  R@3=0.0000  F1@3=0.0000  [relevant: 0/3, total_rel: 1]
  Q09: P@3=1.0000  R@3=0.2308  F1@3=0.3750  [relevant: 3/3, total_rel: 13]
  Q10: P@3=1.0000  R@3=0.3000  F1@3=0.4615  [relevant: 3/3, total_rel: 10]
  Q11: P@3=0.3333  R@3=0.1667  F1@3=0.2222  [relevant: 1/3, total_rel: 6]
  Q12: P@3=0.6667  R@3=0.5000  F1@3=0.5714  [relevant: 2/3, total_rel: 4]
  Q13: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]
  Q14: P@3=0.3333  R@3=0.5000  F1@3=0.4000  [relevant: 1/3, total_rel: 2]
  Q15: P@3=0.3333  R@3=1.0000  F1@3=0.5000  [relevant: 1/3, total_rel: 1]

  ► D_400_50 k=3:  Mean P@3=0.4667  Mean R@3=0.4638  Mean F1@3=0.3618

──────────────────────────────────────────────────────────────────────
Config: D_400_50 | k=5
──────────────────────────────────────────────────────────────────────
  Q01: P@5=1.0000  R@5=0.2941  F1@5=0.4545  [relevant: 5/5, total_rel: 17]
  Q02: P@5=0.2000  R@5=0.3333  F1@5=0.2500  [relevant: 1/5, total_rel: 3]
  Q03: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q04: P@5=0.4000  R@5=1.0000  F1@5=0.5714  [relevant: 2/5, total_rel: 2]
  Q05: P@5=0.0000  R@5=0.0000  F1@5=0.0000  [relevant: 0/5, total_rel: 5]
  Q06: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q07: P@5=0.6000  R@5=0.3750  F1@5=0.4615  [relevant: 3/5, total_rel: 8]
  Q08: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q09: P@5=1.0000  R@5=0.3846  F1@5=0.5556  [relevant: 5/5, total_rel: 13]
  Q10: P@5=0.8000  R@5=0.4000  F1@5=0.5333  [relevant: 4/5, total_rel: 10]
  Q11: P@5=0.2000  R@5=0.1667  F1@5=0.1818  [relevant: 1/5, total_rel: 6]
  Q12: P@5=0.4000  R@5=0.5000  F1@5=0.4444  [relevant: 2/5, total_rel: 4]
  Q13: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]
  Q14: P@5=0.2000  R@5=0.5000  F1@5=0.2857  [relevant: 1/5, total_rel: 2]
  Q15: P@5=0.2000  R@5=1.0000  F1@5=0.3333  [relevant: 1/5, total_rel: 1]

  ► D_400_50 k=5:  Mean P@5=0.3867  Mean R@5=0.5969  Mean F1@5=0.3603

──────────────────────────────────────────────────────────────────────
Config: D_400_50 | k=7
──────────────────────────────────────────────────────────────────────
  Q01: P@7=0.8571  R@7=0.3529  F1@7=0.5000  [relevant: 6/7, total_rel: 17]
  Q02: P@7=0.1429  R@7=0.3333  F1@7=0.2000  [relevant: 1/7, total_rel: 3]
  Q03: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q04: P@7=0.2857  R@7=1.0000  F1@7=0.4444  [relevant: 2/7, total_rel: 2]
  Q05: P@7=0.0000  R@7=0.0000  F1@7=0.0000  [relevant: 0/7, total_rel: 5]
  Q06: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q07: P@7=0.7143  R@7=0.6250  F1@7=0.6667  [relevant: 5/7, total_rel: 8]
  Q08: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q09: P@7=0.8571  R@7=0.4615  F1@7=0.6000  [relevant: 6/7, total_rel: 13]
  Q10: P@7=0.7143  R@7=0.5000  F1@7=0.5882  [relevant: 5/7, total_rel: 10]
  Q11: P@7=0.1429  R@7=0.1667  F1@7=0.1538  [relevant: 1/7, total_rel: 6]
  Q12: P@7=0.2857  R@7=0.5000  F1@7=0.3636  [relevant: 2/7, total_rel: 4]
  Q13: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]
  Q14: P@7=0.1429  R@7=0.5000  F1@7=0.2222  [relevant: 1/7, total_rel: 2]
  Q15: P@7=0.1429  R@7=1.0000  F1@7=0.2500  [relevant: 1/7, total_rel: 1]

  ► D_400_50 k=7:  Mean P@7=0.3238  Mean R@7=0.6293  Mean F1@7=0.3326

Grid search complete!

In [37]:
df_grid = pd.DataFrame(grid_results)

print("=" * 70)
print("GRID SEARCH RESULTS — Mean Precision@K per (Config, k)")
print("=" * 70)
df_grid

======================================================================
GRID SEARCH RESULTS — Mean Precision@K per (Config, k)
======================================================================

,config,k,mean_precision_at_k,mean_recall_at_k,mean_f1_at_k,std_precision_at_k,min_precision_at_k,max_precision_at_k
0,A_600_100,3,0.466667,0.517460,0.410476,0.328537,0.0,1.000000
1,A_600_100,5,0.333333,0.575132,0.356069,0.269037,0.0,1.000000
2,A_600_100,7,0.295238,0.675397,0.357325,0.238231,0.0,0.857143
3,B_800_200,3,0.444444,0.544683,0.404911,0.325300,0.0,1.000000
4,B_800_200,5,0.360000,0.646429,0.389536,0.284856,0.0,1.000000
5,B_800_200,7,0.304762,0.713175,0.368992,0.246649,0.0,0.857143
6,C_900_150,3,0.444444,0.581349,0.438384,0.299912,0.0,1.000000
7,C_900_150,5,0.346667,0.696429,0.407509,0.255976,0.0,1.000000
8,C_900_150,7,0.276190,0.736508,0.357249,0.232032,0.0,0.857143
9,D_400_50,3,0.466667,0.463816,0.361811,0.328537,0.0,1.000000
10,D_400_50,5,0.386667,0.596916,0.360336,0.315926,0.0,1.000000
11,D_400_50,7,0.323810,0.629299,0.332603,0.298034,0.0,0.857143

In [27]:
print("=" * 70)
print("Pivot Tables: Mean Metrics per (Config, k)")
print("=" * 70)

print("\n── Precision@K ──")
pivot_p = df_grid.pivot(index="config", columns="k", values="mean_precision_at_k")
display(pivot_p)

print("\n── Recall@K ──")
pivot_r = df_grid.pivot(index="config", columns="k", values="mean_recall_at_k")
display(pivot_r)

print("\n── F1@K ──")
pivot_f1 = df_grid.pivot(index="config", columns="k", values="mean_f1_at_k")
display(pivot_f1)

======================================================================
Pivot Tables: Mean Metrics per (Config, k)
======================================================================

── Precision@K ──

k                 3         5         7
config
A_600_100  0.466667  0.333333  0.295238
B_800_200  0.444444  0.360000  0.304762
C_900_150  0.444444  0.346667  0.276190

── Recall@K ──

k                 3         5         7
config
A_600_100  0.517460  0.575132  0.675397
B_800_200  0.544683  0.646429  0.713175
C_900_150  0.581349  0.696429  0.736508

── F1@K ──

k                 3         5         7
config
A_600_100  0.410476  0.356069  0.357325
B_800_200  0.404911  0.389536  0.368992
C_900_150  0.438384  0.407509  0.357249

In [28]:
# best_idx = df_grid["mean_precision_at_k"].idxmax()
# best = df_grid.iloc[best_idx]

# print(f"Best Combination:")
# print(f"  Config:            {best['config']}")
# print(f"  k:                 {int(best['k'])}")
# print(f"  Mean Precision@K:  {best['mean_precision_at_k']:.4f}")
# print(f"  Std Precision@K:   {best['std_precision_at_k']:.4f}")
# print(f"  Min Precision@K:   {best['min_precision_at_k']:.4f}")
# print(f"  Max Precision@K:   {best['max_precision_at_k']:.4f}")

In [29]:
# df_grid.to_csv("grid_search_results.csv", index=False)

# print("Saved:")
# print("grid_search_results.csv")

In [38]:
!pip install rank_bm25 --break-system-packages -q

In [39]:
from rank_bm25 import BM25Okapi

def build_bm25_index(chunks):
    """chunks: list of langchain Document objects"""
    tokenized_corpus = [doc.page_content.lower().split() for doc in chunks]
    bm25 = BM25Okapi(tokenized_corpus)
    return bm25, chunks  # keep chunks aligned with tokenized_corpus by index

bm25_a, corpus_a = build_bm25_index(chunks_a)
bm25_b, corpus_b = build_bm25_index(chunks_b)
bm25_c, corpus_c = build_bm25_index(chunks_c)

BM25_INDEXES = {
    "A_600_100": (bm25_a, corpus_a),
    "B_800_200": (bm25_b, corpus_b),
    "C_900_150": (bm25_c, corpus_c),
}

In [40]:
# %%
def hybrid_search(query, config_name, k_final=5, pool_size=20, alpha=0.5):
    """
    alpha=1.0 -> pure dense
    alpha=0.0 -> pure BM25
    alpha=0.5 -> equal blend
    """
    vs = VECTORSTORES[config_name]
    bm25, corpus = BM25_INDEXES[config_name]

    # --- Dense side ---
    dense_results = retrieve_topk(query, k=pool_size, vs=vs)  # [(doc, distance), ...]
    # Chroma distance: smaller = more similar. Convert to a similarity-like score.
    dense_scores = {id(doc): 1 / (1 + dist) for doc, dist in dense_results}

    # --- BM25 side ---
    tokenized_query = query.lower().split()
    bm25_raw_scores = bm25.get_scores(tokenized_query)
    top_bm25_idx = sorted(range(len(bm25_raw_scores)), key=lambda i: bm25_raw_scores[i], reverse=True)[:pool_size]
    max_bm25 = max(bm25_raw_scores) if max(bm25_raw_scores) > 0 else 1
    bm25_results = [(corpus[i], bm25_raw_scores[i] / max_bm25) for i in top_bm25_idx]
    bm25_scores = {id(doc): score for doc, score in bm25_results}

    # --- Merge candidate pools from both methods ---
    all_docs = {id(doc): doc for doc, _ in dense_results}
    all_docs.update({id(doc): doc for doc, _ in bm25_results})

    merged = []
    for key, doc in all_docs.items():
        d_score = dense_scores.get(key, 0)
        b_score = bm25_scores.get(key, 0)
        combined = alpha * d_score + (1 - alpha) * b_score
        merged.append((doc, combined))

    merged.sort(key=lambda x: x[1], reverse=True)
    return merged[:k_final]

In [41]:
# %%
for qid in ["Q05", "Q08"]:
    q = next(x["question"] for x in TEST_QUESTIONS if x["id"] == qid)
    print(f"\n{'='*80}\n{qid}: {q}\n{'='*80}")

    print("\n--- Dense only (alpha=1.0) ---")
    for rank, (doc, score) in enumerate(hybrid_search(q, "A_600_100", k_final=5, alpha=1.0), 1):
        print(f"[{rank}] score={score:.4f} p.{doc.metadata.get('page_number')} :: {doc.page_content[:100]}...")

    print("\n--- Hybrid (alpha=0.5) ---")
    for rank, (doc, score) in enumerate(hybrid_search(q, "A_600_100", k_final=5, alpha=0.5), 1):
        print(f"[{rank}] score={score:.4f} p.{doc.metadata.get('page_number')} :: {doc.page_content[:100]}...")

    print("\n--- BM25 only (alpha=0.0) ---")
    for rank, (doc, score) in enumerate(hybrid_search(q, "A_600_100", k_final=5, alpha=0.0), 1):
        print(f"[{rank}] score={score:.4f} p.{doc.metadata.get('page_number')} :: {doc.page_content[:100]}...")

================================================================================
Q05: How does the NICE guideline define the "white-coat effect"?
================================================================================

--- Dense only (alpha=1.0) ---
[1] score=0.7118 p.17 :: 2.5 Certainty of evidence and strength of recommendations
The GDG rated the certainty of evidence a...
[2] score=0.7069 p.17 :: (e.g. adverse effects). The strength of recommendations in this guideline was graded into two
categ...
[3] score=0.6951 p.22 :: step to indicate treatment.
Evidence and rationale
The most direct evidence is derived from an indiv...
[4] score=0.6931 p.12 :: For a short explanation of why the committee deleted the recommendation on
relaxation therapies and...
[5] score=0.6927 p.42 :: (13)
Rubinstein A, Colantonio L, Bardach A, Caporale J, Martí SG, Kopitowski K, et al. Estimation o...

--- Hybrid (alpha=0.5) ---
[1] score=0.5000 p.50 :: Finding more information and committee
details
To find NICE guidance on related topics, including ...
[2] score=0.3904 p.19 :: antagonists: not for use in pregnancy, how to use for breastfeeding and
clarification on breastfeed...
[3] score=0.3779 p.14 :: This guideline will replace the guidance in the modules Evidence-based protocols and Risk-based CVD ...
[4] score=0.3631 p.12 :: For a short explanation of why the committee deleted the recommendation on
relaxation therapies and...
[5] score=0.3559 p.17 :: 2.5 Certainty of evidence and strength of recommendations
The GDG rated the certainty of evidence a...

--- BM25 only (alpha=0.0) ---
[1] score=1.0000 p.50 :: Finding more information and committee
details
To find NICE guidance on related topics, including ...
[2] score=0.7808 p.19 :: antagonists: not for use in pregnancy, how to use for breastfeeding and
clarification on breastfeed...
[3] score=0.7559 p.14 :: This guideline will replace the guidance in the modules Evidence-based protocols and Risk-based CVD ...
[4] score=0.7261 p.12 :: For a short explanation of why the committee deleted the recommendation on
relaxation therapies and...
[5] score=0.6753 p.44 :: available on drug treatments for hypertension were not included in this review because
they were de...

================================================================================
Q08: What specific warnings does the NICE guideline provide regarding the use of salt substitutes containing potassium chloride?
================================================================================

--- Dense only (alpha=1.0) ---
[1] score=0.7414 p.11 :: 1.4.1
Offer lifestyle advice to people with suspected or diagnosed hypertension, and
continue to o...
[2] score=0.7389 p.51 :: Update information
February 2026: We added recommendation 1.2.11 to offer advice on healthy living ...
[3] score=0.7307 p.19 :: antagonists: not for use in pregnancy, how to use for breastfeeding and
clarification on breastfeed...
[4] score=0.7191 p.23 :: • Discuss adherence (see recommendation 1.4.40). [2019]
1.4.48
For people with confirmed resistant...
[5] score=0.7183 p.52 :: groups
• the information on when to refer to the hypertension in pregnancy guideline was made
clea...

--- Hybrid (alpha=0.5) ---
[1] score=0.5000 p.11 :: 1.4.1
Offer lifestyle advice to people with suspected or diagnosed hypertension, and
continue to o...
[2] score=0.4211 p.14 :: This guideline will replace the guidance in the modules Evidence-based protocols and Risk-based CVD ...
[3] score=0.3707 p.11 :: 1.4.1
Offer lifestyle advice to people with suspected or diagnosed hypertension, and
continue to o...
[4] score=0.3695 p.51 :: Update information
February 2026: We added recommendation 1.2.11 to offer advice on healthy living ...
[5] score=0.3653 p.19 :: antagonists: not for use in pregnancy, how to use for breastfeeding and
clarification on breastfeed...

--- BM25 only (alpha=0.0) ---
[1] score=1.0000 p.11 :: 1.4.1
Offer lifestyle advice to people with suspected or diagnosed hypertension, and
continue to o...
[2] score=0.8422 p.14 :: This guideline will replace the guidance in the modules Evidence-based protocols and Risk-based CVD ...
[3] score=0.5854 p.29 :: Other recommendations for research
6 Same-day hospital specialist assessment
Which people with ext...
[4] score=0.5715 p.51 :: Update information
February 2026: We added recommendation 1.2.11 to offer advice on healthy living ...
[5] score=0.5588 p.13 :: drugs as well as single-pill combinations in this current guideline.
Scope and objectives of the hyp...

In [42]:
def search_corpus_for_phrase(phrase, chunks):
    matches = []
    for i, doc in enumerate(chunks):
        if phrase.lower() in doc.page_content.lower():
            matches.append((i, doc))
    return matches

# Check Q05
matches_q05 = search_corpus_for_phrase("white-coat", chunks_a)
print(f"'white-coat' found in {len(matches_q05)} chunks")
for i, doc in matches_q05:
    print(f"  chunk {i}, page {doc.metadata.get('page_number')}: {doc.page_content[:200]}")

# Check Q08
matches_q08 = search_corpus_for_phrase("potassium", chunks_a)
print(f"\n'potassium' found in {len(matches_q08)} chunks")
for i, doc in matches_q08:
    print(f"  chunk {i}, page {doc.metadata.get('page_number')}: {doc.page_content[:200]}")

'white-coat' found in 4 chunks
  chunk 102, page 15: • hypertension (with or without type 2
diabetes) or
• type 1 diabetes (regardless of
albumin to creatinine ratio)
Below
150/90
Recommendation 1.4.21
NICE's guideline on type 1
diabetes in adul
  chunk 113, page 26: daytime average or HBPM average blood pressure ranging from 135/85 mmHg to 149/
94 mmHg.
Stage 2 hypertension
Clinic blood pressure of 160/100 mmHg or higher but less than 180/120 mmHg and
subseque
  chunk 119, page 32: arm blood pressure is associated with an increased risk of cardiovascular events, possibly
due to vascular damage.
ABPM correlates well with invasive blood pressure measurement and can identify both
  chunk 124, page 37: The committee decided to retain the 2011 recommendation on using clinic blood pressure,
but also agreed that the updated guideline should support home monitoring for people
who wish to use it. The c

'potassium' found in 7 chunks
  chunk 52, page 40: 6.2 Drug- and dose-specific protocols
Two examples of suggested drug and dose-specific protocols are presented below (Figs 5 and 6). These
should be viewed as examples and other approaches are possib
  chunk 53, page 40: If BP is not at goal,
refer to a specialist.
NOTE: Monitor potassium and
kidney function when starting or
changing the dose of ACEi/ARB
or thiazide/thiazide-like diuretic, if
testing is readily a
  chunk 54, page 41: Algorithm 2: Initiation of treatment not using a single-pill combination (i.e. with monotherapy
or free combination therapy)
[
[ A CCB, rather than a thiazide-type diuretic or ACEi/ARB, was selected
  chunk 55, page 41: or chlorthalidone 12.5 mg
once a day).
If BP is not at goal, increase
the thiazide/thiazide-like
diuretic (double the dose to
hydrochlorothiazide 50 mg or
chlorthalidone 25 mg
once a day).
If B
  chunk 98, page 11: 1.4.1
Offer lifestyle advice to people with suspected or diagnosed hypertension, and
continue to offer it periodically. [2004]
1.4.2
Ask about people's diet and exercise patterns because a healthy
  chunk 110, page 23: • Discuss adherence (see recommendation 1.4.40). [2019]
1.4.48
For people with confirmed resistant hypertension, consider adding a fourth
antihypertensive drug as step 4 treatment or seeking specia
  chunk 132, page 45: Why the committee made the recommendations
No evidence on step 4 treatment was identified that could be used to formulate new
recommendations. However, the committee reviewed the 2011 recommendation